### ISSUE TITLE
echo arena not starting

### ISSUE THREAD

**Issue by biggiesmallss** [LibreVR/Revive#1015]
ever since the echo arena update for the combat beta, it is not starting with revive. other oculus games work, but not echo arena. i just get stuck in the white loading screen

**Comment by Grillsen** [comment]
I'm having the same issue

**Comment by Dragoboss** [comment]
To clarify this more:

EchoVR, the new combined name for Echo Arena and Echo Combat does not launch in Remixed (does in Revive) assumingly due to the engine changes in introducing Echo Combat.

Even with the newer SteamVR input controls for 1.4.0, we are unable to swap touchpad for thumbstick (we can for turning but not for pressing the thumbstick) therefore we cannot play with the same controls as we use on Remixed.

Which, I guess, is not a major problem (the input).
To confirm this closer:
Echo Arena always worked fine in Remixed, but Echo Combat closed beta (at the time) gave a 'bugsplat' crash right away upon attempting to launch.
Since these changes are now integrated into one executable I am assuming the fault lies within EC, not EA.

**Comment by biggiesmallss** [comment]
@dragoboss sorry, what is remixed?

**Comment by biggiesmallss** [comment]
But I play on the Vive, and it doesnt work

**Comment by reaper317** [comment]
Doesn't launch at all in 1.3. On 1.4 it wouldn't recognize any controller input,  but it did track them. For WMR

**Comment by Dragoboss** [comment]
@biggiesmallss curious, ReVive works fine for me....

**Comment by Armada651** [comment]
The problem is that EchoVR update changed the executable name and Revive doesn't update that information for games that have already been installed. **You need to re-install either EchoVR or Revive, that will update the executable information.**

This is the reason why it launches for people in 1.4, not because anything changed in that version but because it caused Revive to refresh the cached data about each game.

**Comment by Dragoboss** [comment]
@Armada651 
This is not the case for Remixed, though.
I have reinstalled several times.
I also couldn't start the EC closed beta when it came out a few weeks ago, now that is a new install / new executable.

Now with the new EchoVR, I cannot start it either.
Any tips for that?

**Comment by Armada651** [comment]
Remixed is still in beta, it's not as compatible as Revive yet.

**Comment by Dragoboss** [comment]
I am aware of that I just hoped you might know where the issues lie or how to fix it or even a work-around.

**Comment by reaper317** [comment]
I'll uninstall both revive and echo vr.  Should I install echo first, then revive?  Revive 1.3 I'm assuming?

**Comment by Armada651** [comment]
@reaper317 You're exaggerating you only need to re-install either, I recommend re-installing Revive. You don't have to uninstall first, just install the latest **stable** release over your existing installation and you're done.

**Comment by Grillsen** [comment]
I reinstalled echo vr and revive and that fixed it. However launching any game through revive with steam vr beta will crash

**Comment by reaper317** [comment]
I will have to attempt this weekend

**Comment by Dragoboss** [comment]
Issue went stale.

If you want to try with latest version make sure to disable motion smoothing before launcghing Echo as it breaks their engine.
Re-post a new ticket if still needed after that.
