### ISSUE TITLE
(Rift user) Better performance on my oculus games revived to steamvr! But no button mappings when using oculus controllers?!

### ISSUE THREAD

**Issue by antuanos** [LibreVR/Revive#1078]
Great work with the revive! It gives HUGE performance boosts on a lot of oculus titles (I'm an oculus owner). But can only watch the first screen because my touch controllers don't get a button mapping from revive. Is there any solution to this?

I've tried to map manually at the first settings screen where it says the controllers are unmapped to the game I'm running, but it doesn't seem to help at all.

**Comment by Armada651** [comment]
Revive is not intended to be used by Oculus Rift headsets, if you're getting a performance boost there may be something wrong with your Oculus Runtime configuration.

**Comment by Armada651** [comment]
Version 1.6.0 now adds a rudimentary binding for Oculus Touch controllers, but it is only half-complete. The menu button can't be bound because it's in use by SteamVR as the dashboard button.

Also, the SteamVR Oculus driver has a bug that makes the touched state for all the buttons on the right controller inaccessible, so those only work on the left controller.
