### ISSUE TITLE
Problems with Remixed 1.5 “fatal error” crash

### ISSUE THREAD

**Issue by neftavazquez** [LibreVR/Revive#1083]
I updated oculus software and revive 1.5 yesterday night and I have problem when starting games, says “game crashed and will close “FATAL ERROR” I can’t play games, I tried with steam Vr beta and open ver and I have the same problem yet.

**Comment by reksider** [comment]
Hi there, 
I got the same problem for every single game launch via remixed since the last update (some are working through Steam VR)
I send to you the Bigscreen error log file attached in this comment. 
[error.log](https://github.com/LibreVR/Revive/files/2487126/error.log)
And here is the error log from Robo call with remixed : 
Hope it will help you, and congrat, I love your work! Keep up man! 
By the way, do you have a Patreon or something similar?

Log file open, 10/17/18 13:18:09
LogInit:Display: Running engine for game: RoboRecall
LogInit:Display: Project file not found: ../../../RoboRecall/RoboRecall.uproject
LogInit:Display: 	Attempting to find via project info helper.
LogUProjectInfo: Found projects:
LogPlatformFile: Not using cached read wrapper
LogInit:Display: RandInit(-1264586664) SRandInit(-1264586663).
LogTaskGraph: Started task graph with 4 named threads and 7 total threads with 1 sets of task threads.
LogInit: Using libcurl 7.47.1
LogInit:  - built for x86_64-pc-win32
LogInit:  - supports SSL with OpenSSL/1.0.2g
LogInit:  - supports HTTP deflate (compression) using libz 1.2.8
LogInit:  - other features:
LogInit:      CURL_VERSION_SSL
LogInit:      CURL_VERSION_LIBZ
LogInit:      CURL_VERSION_IPV6
LogInit:      CURL_VERSION_ASYNCHDNS
LogInit:      CURL_VERSION_LARGEFILE
LogInit:      CURL_VERSION_IDN
LogInit:  CurlRequestOptions (configurable via config and command line):
LogInit:  - bVerifyPeer = false  - Libcurl will NOT verify peer certificate
LogInit:  - bUseHttpProxy = false  - Libcurl will NOT use HTTP proxy
LogInit:  - bDontReuseConnections = false  - Libcurl will reuse connections
LogInit:  - CertBundlePath = nullptr  - Libcurl will use whatever was configured at build time.
LogOnline:Display: Oculus: FOnlineSubsystemOculus::InitWithWindowsPlatform()
[error.log](https://github.com/LibreVR/Revive/files/2487099/error.log)

**Comment by Armada651** [comment]
Fixed in the latest release, problem was two typos in the code. Sorry about that.

**Comment by reksider** [comment]
Ho yeah ! Thanks a lot for your fix, everything works now after your update on Steam VR :D. But unfortunately, nothing works with Remixed. I clic on every single game from the Revive dashboard, and  nothing pop up, only with Robo recall with the UE4 crash repport. The windows mixed reality don't even react when I clic on something.... I have already uninstall/reinstall Oculus and Revive too, nothing change. 

The only thing I notice is my WMR right after the installation of Revive the loading screen appear  (with the one with small triangle everywhere), then it's going back to the MS lobby. 
I got the october update from Microsoft, since then, Remixed is not working, maybe that's why....

**Comment by enrekatr** [comment]
Revive 1.5 and steam beta works for me in roborecall.
Can u try this combination (or with steam hot fix version) and give feedback here?
(ps my wmr hmd is Samsung)
