### ISSUE TITLE
Bypass DRM?

### ISSUE THREAD

**Issue by AnthonyPaulO** [LibreVR/Revive#110]
I'm confused... do you understand what exclusive rights means? There's a difference between buying a right vs buying an exclusive right; you pay a certain price for a right, but you pay a much higher price for an exclusive right... it really doesn't take a genius to understand this concept. Oculus has exclusive rights to certain software which means you only have the right to play it on Oculus hardware. Yet here you are bypassing their DRM in order to make it run on the competitor's hardware and making it available to the rest of the world, essentially robbing Oculus of the premium they paid for exclusive access; this is called "theft" because you robbed them of the benefits they would accrue from the premium they paid, so in the end they paid extra and got nothing in return. (And when I say "paid" it doesn't necessarily have to be monetary, payment can come in many forms) You claim you "didn't want to go down that path" but there were clearly other paths available, including a) don't play the exclusive content or b) buy the Oculus hardware and play the exclusive content legally. Nobody put a gun to your head and forced you to do this, you only did this for your selfish needs! I've been a hardcore gamer ever since the Apple ][ and I'm all about openness, but whenever I want to use something I buy it LEGALLY.You clearly deserve whatever legal wrath Oculus is about to dump on you.

**Comment by Fidelix** [comment]
Can someone mark this as "Won't fix", please?

We have a troll here.

**Comment by Zanoh** [comment]
Yeah, op, because we all have 1400+ lying around. Listen dirtbag, many of us want to support the games, but hate the closed garden approach. Especially when it's on an OPEN platform.

Get off your high arse. The programmers and users here want to support good games, and want to enjoy all that VR has to offer. That isn't a bad desire as a consumer nor should we be shamed for it. VR is a niche, trying to close off an already niche market is business suicide. So there is absolutely no harm in what we are doing, buying the games we want, and playing it on the HMD we prefer.
