### ISSUE TITLE
Binding issues

### ISSUE THREAD

**Issue by marcocorriero** [LibreVR/Revive#1103]
Well, i can't use default Rift control without rebinding everything, and is a bad binding option, why you dont capture the button clicked and set that as a bind? 

or select "Default Binding" , aka ignore the binding options and use the controllers like it should work.

**Comment by Dragoboss** [comment]
The SteamVR binding system that Revive use, basis its default on whatever the Dev for that game has set as default bindings.
Revive ultimately was made for Vive and later slightly adapted/used also for WMR, even though that was not intended.

There are no default bindings for Oculus Rift Touch because it makes no sense using Revive for Oculus games when you can just use Oculus directly.
Therefore, there are no default bindings for Oculus Touch.
You could create them, but neither the Revive dev nor I have a Rift to our disposal right now to do this.
