### ISSUE TITLE
Injection option not available?

### ISSUE THREAD

**Issue by TheMrAwesomeness** [LibreVR/Revive#1124]
I found out Revive is the way to play Rift-only PC games if you have a Vive.  To be specific, I'm using Trinus PSVR to make my PC think I'm using a Vive.  The Vive Home seems to work fine.  It seems Revive works well playing the pre-installed games, such as Dreamdeck.  However, I am trying to play games that are not part of the Oculus library (more specifically, I am trying to use the VBJin Virtual Boy emulator).  The Revive Overlay pops up just fine when I click on it in the Start menu, after I have Trinus PSVR, the SteamVR home, and the Oculus program up and running.  However, I cannot seem to find a way to inject games into Revive.  If it helps to know, the Revive Overlay doesn't pop up from "show hidden icons," I only see it in the taskbar.  If I right click on the Revive Overlay from the Task Bar, I only see an option to start the Revive Overlay.  Does anyone know why the Inject option isn't popping up?

**Comment by DavidRayner** [comment]
I'm new to this so haven't tested this myself but try dragging the game's exe onto one of the ReviveInjector exe - mine are located in `C:\Program Files\Revive\Revive`

**Comment by TheMrAwesomeness** [comment]
Thank you for the tip.  I also saw on a guide someone made on the Steam comminity that said this http://oi65.tinypic.com/51btxg.jpg .  When I get home tonight, I will test out both these possible solutions.

**Comment by Dragoboss** [comment]
Just for the record,
games not part of the Oculus Library, are they part of the Steam Library? In that case do not use Revive either.

If the games are FULLY standalone, do not use SteamVR or Oculus, you can use the Revive inject and/or patch feature.
Try if it works with Inject first, if so, you can patch for permanent use (or until they update the binary).

Because of no further response for 11 days I am assuming this issue is fixed. If not feel free to reopen the ticket or create a new updated with the current situation.

**Comment by fredmarkette** [comment]
Question:  I am new to the PC world and am trying to integrate simulator training for my high school aviation/aerospace club.  Using Condor2 with Vive / Revive... I followed the directions in the Condor2 user manual.   However, I am stuck in that the only programs that show up on my Revive Dashboard are just the four and I do not see the inject option when I right click.  How do I inject or "patch" Condor2 so that it will run in 3D using Revive?
