### ISSUE TITLE
Echo VR Jitter

### ISSUE THREAD

**Issue by mindrush12** [LibreVR/Revive#1127]
I can run games like Fallout 4 non problem, but Echo VR jitters especially when I move my head. I read it could be USB bandwidth issue but not sure and I don't know how to test that.

**Comment by Armada651** [comment]
Which headset? If it's a WMR headset are you using the SteamVR version of Revive or the native Remixed version?

**Comment by mindrush12** [comment]
I am using the HTC Vive and Steam VR version as in I open the menu and I click the revive option in the HUD.

**Comment by mindrush12** [comment]
Let me know what other information you need.

**Comment by Dragoboss** [comment]
Some details on your computer's specs would be helpful and possibly keep an eye on your resources while running it (in lobby or match).
How much% does your cpu run at?

**Comment by mindrush12** [comment]
![echo](https://user-images.githubusercontent.com/45593881/49493754-9299cc80-f85d-11e8-8e9b-a7c9e52a865d.JPG)

**Comment by mindrush12** [comment]
Maybe it's a usb bandwidth issue? How do I tell? or turn haptics off?

**Comment by Dragoboss** [comment]
More useful right now would be cpu usage rather than timings. In example your Taskmanager on the resources tab, then CPU.
That way we can see cpu percentage and temperature.

Could be USB bandwidth but that'd mean you'd have it in more games, not just Echo, presumably. However echo is more intensive than most. I'd compare to sprint vector or something the like.

**Comment by mindrush12** [comment]
![image](https://user-images.githubusercontent.com/45593881/49533110-711cfd00-f8be-11e8-9f1e-28fd6fdfa548.png)

**Comment by mindrush12** [comment]
Accidentally closed. After the new update it still jittery when I move my head. Clear if I keep still.

**Comment by sotobon** [comment]
good i have the same problem with wmr i have an i7-7700k, gygabyte z170x designare plate, 1080 gtx, hard drive 970 evo nvme m.2 and when i move my head it trembles all this only happens with oculus games in the steam games It's all right, I can touch some of the configuration to correct it. thank you

**Comment by mindrush12** [comment]
Here is the CPU usage. https://imgur.com/a/Su0itfz

**Comment by mindrush12** [comment]
![ja4kqmj](https://user-images.githubusercontent.com/45593881/49601768-084d8780-f987-11e8-908c-0883af027220.jpg)

**Comment by mindrush12** [comment]
Games like Fallout 4 and Sprint vector look fine and don't have jitter.

**Comment by cappaholic** [comment]
I’m on WMR, and have had the exact same issue in TribeXR. It’s only been in the last week or two. I feel like it’s due to a SteamVR update. I think 1.1.3 and Motion Smoothing came out around that time.

**Comment by FoxtrotD** [comment]
same problem here, dont worry guy, your problem is the same as ours. I have 100 hours of play with steamvr and revive, with windows mixed reality WMR, Dell Visor, Rx 480. All the games have always worked perfect with revive, I never use remixed. With my dell visor brass tactics, echo combat, contact, robo recall they worked perfect, but since the update of steam 1.1.3 everything works badly, very badly. Plant the screen.

let's hope it is resolved. Thanks in advance

**Comment by GoldRyan** [comment]
I'm having the same problem. Any updates?

**Comment by Armada651** [comment]
Jitter issues have been fixed in the latest pre-release: https://github.com/LibreVR/Revive/releases/tag/1.7.0
