### ISSUE TITLE
ONWARD on WMR not working anymore

### ISSUE THREAD

**Issue by kodama12** [LibreVR/Revive#1141]
Hi guy,
First, thanxs for your Revive mod .
After 1 year of playing, i stopped onward; it was fine. I've just update Revive, Oculus, SteamVR & drivers of GPU, and ONWARD refuse to launch, or more precisely, the screen is not redirected/injected inside VR headset. I hear the sound, but i'm still inside the "white room" of STEAMVR. On my computer, the window of Onward is opened, but white, nothing appears.

Any idea about ?

**Comment by Armada651** [comment]
Onward on SteamVR is not using Revive. Whatever problem you're having with Onward it's not related to updating Revive.

**Comment by kodama12** [comment]
I use Onward on Oculus, with Revive...

**Comment by kodama12** [comment]
andi launch it in Steam VR, like usual.... dont be silly....

**Comment by Dragoboss** [comment]
First of all, don't quote Armada back to Armada.
You're being rather obnoxious, and frankly, don't tell Armada to read the manual, because he WROTE the manual.

Now on top of ignoring the format and creating an immediate duplicate after a close even though you can still comment here, you barely provided any details, like specs, versions, or anything useful at all.
So instead of blaming us for your poor issue reporting skills, start working at giving some details so we can actually diagnose this.
And never, ever, ever again, insult the people who are trying to help you.
