### ISSUE TITLE
buttons not working for injected games

### ISSUE THREAD

**Issue by wstlxx** [LibreVR/Revive#1165]
### Description of the issue
the standalone games injected to revive not responding to controllers button
but the hands are shown 
few weeks ago i played the game well though.not sure what caused that
the situation is just like #1050 but all games from dashboard work perfect.
the GPU driver ,steamvr were surely updated once . nothing else changed i think.

### Technical Information

  - CPU:e31220v2
  - GPU:GTX1060 6G
  - RAM: 8 GB 1600 MHz DDR3L SDRAM
  - OS: Windows 10 - 1809
  - Vive 

#### Versions and features
*This issue is about:*
  - Revive
  - SteamVR version :1.2.7beta(1.2.6 as well)
  - Revive installation version:1.6.2

#### What is the last working version before this issue first came up?
  - Revive installation:1.6.2
  - SteamVR (unless remixed):forgot

### What apps/games are you trying to run?
  - lone echo standalone from some torrent site

## How to reproduce your issue?

  after injecting lone echo.exe and trying to enter the game

## Error messages/codes
  - none

**Comment by Dragoboss** [comment]
First of all let me be clear that we do not support unofficial / pirated games. On top of that we don't know what version of the game this is and what version of the Api it uses. 

Secondly #1050 was supposedly fixed with a later update.

Now then.
I'll try and investigate this a bit more and get back to you later.
