### ISSUE TITLE
Preview immage and names wrong

### ISSUE THREAD

**Issue by Ylluan** [LibreVR/Revive#1308]
**Describe the bug**
On steamvr home, preview images of oculs game not show and names of games are wrong

**To Reproduce**
just run steam vr and look the list of the games

**Expected behavior**

**Environment (please complete the following information):**
 - App: steam vr
 - OS: win 10 pro 1903
 - Headset: index

**Versions (please complete the following information):**
 - Revive: 1.8.0.6
 - SteamVR: 1.7.6

**Additional context**

**Comment by Armada651** [comment]
Make sure you are connected to the internet when you install Revive so it can retrieve the proper name for each title.

**Comment by Ylluan** [comment]
I'm always connected to the internet. but the problem persists

**Comment by Armada651** [comment]
Can you access this page from the computer where you installed Revive? https://www.oculus.com/experiences/rift/909129545868758

You can correct the name in the file `revive.vrmanifest`, but it will reset with every update of Revive. The images haven't worked for me either, seems to be a SteamVR bug because manually changing the image paths doesn't seem to work.

**Comment by Ylluan** [comment]
yes, I have access to the page you told me.
I modified the file like you said and now the names are correct. For images we will wait for a steamvr update. Thank you Armada, with the last version of Revive, all my games run well. Good job
