### ISSUE TITLE
ECHO VR - New "Player Experience" patch broke multiplayer on Revive

### ISSUE THREAD

**Issue by Splinx** [LibreVR/Revive#1359]
Describe the bug
On 2019-10-11 (YYYY-MM-DD), Echo VR released a new "Player Experience" patch. Whilst the game still loads and runs in single-player on revive; it is now impossible to use the wrist menu control to create parties. Prior to this patch creating a party with your friends worked flawlessly - not it is just completely broken.

** Patch details - Echo VR **
Echo VR, version 25.0.367041.0
• Players can access Echo Arena’s new VS AI modes from the Matchmaking Podium.
• Our New Player Experience (NPE) introduces a series of tutorials to help newer players learn about the Echo VR Lobby and the basics of Echo Arena.
• Numerous bug fixes were implemented overall.

To Reproduce

Upgrade Echo VR with the latest patch 25.0.367041.0
Run the latest version of Revive (1.8.1.1 at time of writing)
Start Echo VR and attempt to invite a friend into your party.
You will find that invites intermittently appear on friends wrists but it is impossible to accept.
You may also notice, in the Oculous desktop application, a popup notification stating that the invite was intercepted there.
**Expected behaviour **
The expected behaviour is that you send the invite to an Oculous friend (someone approved on your friends list). They then receive the invite and you are now in a party!

Environment (please complete the following information):

App: Echo VR (25.0.367041.0) & Revive (25.0.367041.0)
OS: Windows 10
Headset: Valve Index
Versions (please complete the following information):

Revive: 25.0.367041.0

**Comment by qlyoung** [comment]
I can take a look at this, but please be aware there is a known issue with accepting party invites under Revive unless you have some piece of Oculus hardware connected, and you may be running into this.

**Comment by Splinx** [comment]
Oh, okay thanks...

My friends and I tried to research revive and Oculus as mich as we could before buying Echo VR.

Can you please point me in the direction of the known issue.

When you say Oculus hardware, does this mean literally purchasing a whole VR kit or is there a sneaky (cheap) workaround?

Thabks for looking into this buddy :)

**Comment by qlyoung** [comment]
I'm not entirely sure this is the same issue since usually parties work for a while, but after transitions between matches you'd get dropped from the party. But you described not being able to join a party at all - and only after the recent Echo update. So this may not be the same bug.

Here is the problem I'm thinking of: https://github.com/LibreVR/Revive/issues/751
Let me know if the behavior you're seeing sounds the same, or if you think it's substantially different.

As noted in that issue, if you have an Oculus tracking sensor connected, this should be sufficient. But those are still like $50 each from Oculus.

>My friends and I tried to research revive and Oculus as mich as we could before buying Echo VR.

But it's free? :) I guess you're talking about Combat, though.

**Comment by Splinx** [comment]
Thanks buddy, this is tremendously useful info.

I have a neighbour who has an oculous so I will try to plug in a tracking sensor and then report back on this thread.

Thanks again.

**Comment by qlyoung** [comment]
@Splinx any update?
