### ISSUE TITLE
Trying to get Adr1ft working.

### ISSUE THREAD

**Issue by noisyboyuk** [LibreVR/Revive#158]
Hi!

I'm trying to get Adr1ft working but the instructions say to use the Steam Patch. I just went to install it but the link is dead: `https://github.com/LibreVR/Revive/releases/download/0.6/RevivePatch.zip`

Also - I've just downloaded the latest Revive and installed it but I have a question about the runtime. To get it working with the last release I followed the instructions to roll back to 1.3. I am now wondering how I make sure that the latest runtime is now 1.5? I can't see an option to update Oculus Home so I downloaded the latest Oculus Home installer and chose "repair". This seemed to update some files but everything in the runtime folder still seems to have the date-stamp from last week rather than today and I can't see what version it is in the details of properties (that didn't work for me with 1.4 or 1.3 either, the info is just blank).

Any thoughts?

Thanks :)

**Comment by gormanj** [comment]
First off, the url is for the older version of revive and links were removed as announced because Oculus removed their hardware check which makes certain routines in the previous version of Revive unnecessary. Version 0.6.2 of Revive is here:
https://github.com/LibreVR/Revive/releases

Second, if you were to go to the Revive compatibility Wiki here:
https://github.com/LibreVR/Revive/wiki/Compatibility-list
You will see a that the description to the Adr1ft entry is linked to instructions.

As per the instructions you will need to press 'A' on the controller three times after seeing "310" or otherwise it will seem as if it is not working.

**Comment by noisyboyuk** [comment]
Thanks for the fast reply :)

Yeah, this is where I'm finding confusion. The reason I was looking for the patch is because those same instructions say "works with the Steam version - use patch, not injector". So when it didn't work I assumed that it was because I hadn't used the patch.

If the patch is no longer required then that's awesome but is it possible that my issue is with the Oculus Rift runtime not being updated to 1.5? From what I can tell it still looks like it has the 1.3 files in the folder from when I rolled back and I can't work out how to update it without a total re-install of Oculus Home (which of course I'd like to avoid as I don't want to re-install all the Rift titles I have installed).

Thanks again for your help!

**Comment by noisyboyuk** [comment]
Hang on - have I gotten confused here? When I read "works with the Steam version" I assumed that meant the steam patch but does it actually mean the Steam version of the game itself? I suspect it does but want to be sure before I buy it twice :P It's been a very long night so it's probably me just being a dumbass.

**Comment by gormanj** [comment]
The steam patch is a download that is in the section for 0.6.2. I have tested version 0.6.0 with Oculus 1.3 and it works. I do not think there is any issue with the versions. You need to follow directions both for the steam patch and Adr1ft when using Revive and it should work. I think ANY combo will work. Just be sure to wait and press "A" on your functional xbox controller THREE times after seeing "310." It may take some time. When I thought it was not working it was because I didn't wait long enough.

**Comment by gormanj** [comment]
Yes, the Steam version (not Oculus home version). I have tried both and have gotten only the one from steam working.

**Comment by gormanj** [comment]
It works for me on 1.3. I think it will probably work with Oculus 1.5.

**Comment by gormanj** [comment]
BTW, you can update Oculus without reinstalling your titles by following these instructions (also confirmed to work by me):
[]https://support.oculus.com/help/oculus/1715420212071737/

**Comment by noisyboyuk** [comment]
Awesome thanks for your help!

I managed to get it working in the end. I had just misunderstood the instructions it seems! Thanks for the info on updating - that's awesome :)
