### ISSUE TITLE
vbjin-ovr doesn't work with current releases as 32 bit support is gone

### ISSUE THREAD

**Issue by Slamy** [LibreVR/Revive#1665]
**Which game or application is your request about?**
vbjin-ovr

**Is your request related to a problem? Please describe.**
The injector is not able to start vbjin-ovr with the lastest version of Revive.
Version 1.7.3.5 is working though when used with the 32 bit injector.

**Describe the solution you'd like**
I would like to have the 32 bit version of the Injector again as part of Revive.

**Describe alternatives you've considered**
It's difficult. I do think that there is no alternative? Maybe a separate distribution of a 32 bit injector?

**Comment by CrossVR** [comment]
Actually the new injector can inject into 32-bit applications without using a separate 32-bit version, However that didn't work due to a bug. The latest beta versions can do it, but they default to OpenXR which SteamVR doesn't support for 32-bit applications.

So your best bet is either using the old version or using the beta version and then enabling "Use legacy version" in the tray icon menu.

**Comment by Slamy** [comment]
It was exactly like you said.
