### ISSUE TITLE
Game/App not showing up in Revive Dashboard - Through the Ages: President Obama Celebrates America's National Parks

### ISSUE THREAD

**Issue by janus1234** [LibreVR/Revive#274]
Hey, was anyone able to watch the above mentioned 360/3D video through Revive? On my PC it simply doesn't show up.

I've already tried the following things:

- Uninstall and reinstall the "game"
- Reinstall Revive
- Install other Oculus Game to check if Revive still works --> works (tried Mountain Goat Mountain)

**Comment by lghtanddrk** [comment]
I can't get the 360/3D video app to work at all.  It worked for me for a time and then one day when I tried to use it everything was suddenly upside down and backwards. Same for the photo viewer app. I think I read somewhere that these apps are not using the latest API or Unity code or something and that's why they don't work with Revive.

**Comment by LibreVR** [comment]
@lghtanddrk You haven't updated to the latest release of Revive, that problem was fixed in 0.9.5.

@janus1234 Through the Ages is explicitly not supported, it does not work well enough to be played with Revive.

**Comment by lghtanddrk** [comment]
How do you see what version you have installed?  Where do I get the latest version or see what the latest version is? Is there a way to sign up to be notified when new updates come out?

**Comment by lghtanddrk** [comment]
I also want to add that I just installed revive about a week and a half ago on a new computer and that's when I started seeing it happen.
