### ISSUE TITLE
Eve Valkyrie crashes on startup with Fatal Error

### ISSUE THREAD

**Issue by Northernhosp** [LibreVR/Revive#278]
New OS (W10) doesn't launch from drag and drop method and game doesn't launch from the dashboard as well but it does show the game on the dashboard. Any assistance?

**Comment by Northernhosp** [comment]
Update, I was able to launch through dashboard using the controllers inside of steam vr. Now the issue is that it launches to a black screen (Eve Valkyrie) and a pop up saying "fatal error".

**Comment by hyperseven** [comment]
look at issue #197

**Comment by Northernhosp** [comment]
I have, including dozens of other post none show this error. Thanks for the input as this was next to the most similar issue but unfortunately where his succeeds is where the error is appearing for me.

**Comment by 994wemj** [comment]
I have the same issue on a new install today. Appear to inject and launch fine, but get an instant UE Fatal Error.

==========ReviveInjector.log==========
Launched injector with: C:\Program Files\Revive\Revive\ReviveInjector_x64.exe /base "Software/ccp-games-newcastle-eve-valkyrie/Image/WindowsNoEditor/VkGame/Binaries/Win64/EVE Valkyrie.exe" -oculus -vr -tenant=live -windowed
Creating process: D:\Oculus\Software\ccp-games-newcastle-eve-valkyrie\Image\WindowsNoEditor\VkGame\Binaries\Win64\EVE Valkyrie.exe -oculus -vr -tenant=live -windowed 
Injecting DLL: C:\Program Files\Revive\Revive\x64\openvr_api.dll
LoadLibrary found at address: 0xb3c2f610
Injecting DLL: C:\Program Files\Revive\Revive\x64\LibRevive64_1.dll
LoadLibrary found at address: 0xb3c2f610
Injected dlls successfully

==========ReviveOverlay.log==========
libpng warning: iCCP: known incorrect sRGB profile
Failed to add manifest file to OpenVR: C:\Program Files\Revive\revive.vrmanifest (VRApplicationError_InvalidManifest)
Loaded manifest from: C:\Program Files\Revive\revive.vrmanifest
Runtime directory: file:///D:/Steam/steamapps/common/SteamVR/
Oculus directory: file:///D:/Oculus/
Loading assets manifest: file:///d:/Oculus/Manifests/ccp-games-newcastle-eve-valkyrie_assets.json
Loading assets manifest: file:///d:/Oculus/Manifests/playful-luckys-tale_assets.json
Found assets bundle ccp-games-newcastle-eve-valkyrie_assets
Loading application manifest: file:///D:/Oculus/Manifests/ccp-games-newcastle-eve-valkyrie.json
Found assets bundle playful-luckys-tale_assets
Loading application manifest: file:///D:/Oculus/Manifests/playful-luckys-tale.json
Found application ccp-games-newcastle-eve-valkyrie
Launching application: ccp-games-newcastle-eve-valkyrie

**Comment by Arayar** [comment]
Heya, same issue here. New install of EVE today. If i use the Revive Injector it says i need to use the launcher. If i start the game via the Vive overlay, i get the fatal error pop up. Any ideas on how to fix this ?

**Comment by LibreVR** [comment]
EVE Valkyrie needs a few command-line parameters, you should start it through the dashboard so these parameters are automatically applied.

I'll try and see if I can reproduce fatal error after launching from the dashboard.

**Comment by 994wemj** [comment]
I get the same error via bat file or dashboard.

**Comment by HonokaZhan** [comment]
I get same Fatal Error

**Comment by LibreVR** [comment]
I've reproduced the error, it's a null pointer exception in SteamVR when retrieving the headset info. I'm not sure what causes it yet though.

**Comment by 994wemj** [comment]
I've had a few friends that play on Rift that have had issues with SteamVR when launching valkyrie this weekend. When launching through oculus store it attempts to launch with steamVR and fails. The only resolution I've seen is that they had to uninstall SteamVR (not steam entirely) in order to launch Valkyrie.

Quick google shows redditors having the same issue:
https://www.reddit.com/r/oculus/comments/56jml8/eve_valkyrie_launching_with_steamvr_on_oculus/

**Comment by HonokaZhan** [comment]
it's related for Oculus 

Not Vive

**Comment by Spork3245** [comment]
Hi everyone, I'm having the same issue. Some people, both Oculus and Vive users, were having this issue back in the July update and I tried the official fix posted on Eve: Valkyrie's forums - unfortunately it did not fix it, so I contacted support and just got a reply:
There was a new patch recently released on October 7th and apparently this is the cause of the error for Vive users. Here's the reply I received after detailing my system specs and what-not:
"Hello again, GM Moon Watcher here,

Could you please confirm you are using an Oculus Rift as well? We have some players that have encountered very similar problems when using HTC Vive after the last patch.

Thank you for your patience.

Best Regards, 
GM Moon Watcher
CCP Customer Support | EVE Online | EVE Valkyrie"

I don't know if this helps in the process of getting Eve up and running again with Revive, but apparently the issue is being caused by the new patch, [2016_R5.1] :(

**Comment by chris79ita** [comment]
same problem! (Fatal error) reVive ...is reDead for EVE V. :(

any suggestions?

**Comment by Northernhosp** [comment]
This has nothing to do with ReVive being the issue.
As seen here its a problem with Eve's recent update.
https://support.evevalkyrie.com/hc/en-us/articles/212765845-SteamVR-Known-Issue-and-Workaround

**Comment by chris79ita** [comment]
Yes but this method can not be use without an O.R.! we can't start the game! I hope that the "problem" with this update is not wanted.... for htc player...

**Comment by pimpsippin** [comment]
Pretty pissed because i just bought the game 2 hours ago and now find out it doesnt work. And you cant get refunds from oculus store.... I have been robbed to the max. Need a fix soon.

**Comment by HonokaZhan** [comment]
Look so Impossible Trouble -_-

**Comment by Northernhosp** [comment]
Okay Everyone!
The Support link doesn't load so I'm guessing... That they are working on it!?!? Fingers crossed Guys I feel your pain if it helps any HOTAS + Game was $200 for me and cant even play it, but I'm sure it will be up soon enough!! (Hopefully before PS4 Launch)

**Comment by Northernhosp** [comment]
News Update!!!
https://www.evevalkyrie.com/articles/news/eve-valkyrie-patch-notes-2016_r5-3
^States the SteamVR issue has been resolved. Haven't had a chance to check it out yet but hopefully it's working now!!

**Comment by chris79ita** [comment]
Yes, problem solved!

**Comment by 994wemj** [comment]
Confirmed working once more :)

**Comment by Northernhosp** [comment]
Indeed it's back up and working just fine everyone.
See you on the battlefield!!
