### ISSUE TITLE
Has anyone tried Obduction with Revive?

### ISSUE THREAD

**Issue by iamwes** [LibreVR/Revive#294]
Just wondering if anyone has tried obduction before i buy it? Hoping it works ok? 

Any info would be great, thank you.

**Comment by hyperseven** [comment]
you would be better off asking in /r/vive since this is for bug tracking.

**Comment by mapotter99** [comment]
I own Obduction on Steam, and I just installed the VR update. 

I just tried using the Steam Revive patch, and I couldn't get it to work. @LibreVR, any advice?

**Comment by mapotter99** [comment]
I've tried both the 64 bit and 32 bit with and without the -VR launch option.

**Comment by LibreVR** [comment]
I'll buy it and find out.

**Comment by LibreVR** [comment]
The version on the Oculus Store works fine, so if you bought it on the Oculus Store you should be able to launch it from the Revive Dashboard without issues.

@mapotter99 You probably put the patch in the wrong location, it needs to be in the `Obduction\Binaries\Win64` subfolder. Also, if it still doesn't work try adding `-mode=ORVR` to the launch options.

**Comment by iamwes** [comment]
Great news thank you very much. Looking forward to this

**Comment by LibreVR** [comment]
You may want to put the graphics settings to Medium though, doesn't seem to preform that well. Also, it doesn't seem to account for the height of the player correctly yet.

**Comment by Layseyla** [comment]
Does this work with the steam version?

**Comment by mapotter99** [comment]
Thanks, LibreVR!

This worked withOUT the "-mode=ORVR".  When launching, just select "Launch on OculusRift in Oculus VR Mode" when prompted.

I used the 64 bit patch.

**Comment by iamwes** [comment]
Does it put you unplayably high like a few other games when running through revive?

**Comment by mapotter99** [comment]
@iamwes,

With revive on the Steam version, your eyes are at ground level when you start.

I placed my Vive headset on the floor and pressed the Xbox One Controller "View" button to reset the elevation. After that, it was at the proper height.

**Comment by iamwes** [comment]
Thanks putting it on the floor does help would ideally need to be a bit higher but will do. 

Imy actually finding the game runs better all on epic (resolution 130)... really smooth, but looks terrible with AA, too blurry. Looks the best with AA on low and foliage turned off as that's just a sharp mess with no AA.

Couple of issues don't know if it's revive related. Crashes out with D3D error (about 3 times now) and I find of you move you head fast it kind of flickers a bit sometimes, no matter if it's on the lowest or highest.

**Comment by LibreVR** [comment]
If you're having stability issues with the 1.0 preview, please rollback to the latest 0.9 release. The 1.0 release is an alpha version.

**Comment by iamwes** [comment]
Ok will try that tomorrow then

**Comment by mgiuca** [comment]
I just tried the Oculus Home version. (Strangely, when I tried it a few days ago, I got this error: 

![It doesn't look like you've purchased Obduction. Please visit the Oculus Store or contact Oculus support if you believe this is in error.](https://cloud.githubusercontent.com/assets/228433/19889367/a7edaa18-a088-11e6-9085-019cd39bb226.png)
"It doesn't look like you've purchased Obduction. Please visit the Oculus Store or contact Oculus support if you believe this is in error."

But now it seems to have gone away because I got into the game. The only issue is it looks blurry when you move your head, and not low-detail, but the two eyes mismatch strikingly, like one eye is being rendered much later than the other. I wonder if that's a ReVive issue or something wrong with the game itself? I tried turning my graphics settings all the way down and it didn't help.

**Comment by mapotter99** [comment]
Sounds like a reprojection issue... try enabling/disabling the two different Reprojection options in the Revive 1.0 preview.

**Comment by mapotter99** [comment]
Sorry, the SteamVR Beta, NOT the Revive 1.0 preview!

**Comment by mgiuca** [comment]
Weird: I checked and it's actually not a blurring between eyes; the double-vision effect happens in each eye (even with one eye closed). It also doesn't show up in the game window *or* in the Display Mirror, only on the actual headset.

@mapotter99 Thanks ... I didn't opt into the beta so I don't know why, but I have an option called "Enable Always-on reprojection" in Developer. Turning that *on* helps. Now I still get some frame stuttering (which I am used to on the Vive), but no double-vision effect. Cheers!

**Comment by mapotter99** [comment]
If you aren't on the Steam Beta track, you should have one Reprojection option under "performance".  You can try disabling that. 

I'd also try enrolling in the SteamVR Beta from the SteamVR properties menu, as it includes several updates to the Reprojection options, including the major addition of Asynchronous Reprojection, which may fix your issue.   The newest Beta lists two Reprojection options under "Performance"... Asynchronous and Interleaved. 

This Beta is required in order to use Revive 1.0 Preview.

**Comment by iamwes** [comment]
I've rolled mine back to 0.90 seems to run most things a lot better than 1.0 preview for me, including Obduction, seems to of stopped the D3D crash
