### ISSUE TITLE
City Car Driving

### ISSUE THREAD

**Issue by KaoReal** [LibreVR/Revive#298]
A version of this game (1.5.2) was released on Steam recently, and it is said to support Oculus. Can't seem to get it to run with any of the Revive methods. Just doesn't show up in the VR world.

**Comment by Adekvantus** [comment]
It dose not work with revive.

**Comment by KeithSedgeman** [comment]
It works with the x86 injector. I remember it taking a fair number of tries to get the "Monitor + Oculus" option to become selectable in video settings, but got there in the end, now it just works when I load it.

I can't remember which planets needed to be in alignment, but I assure you it is possible!

**Comment by Adekvantus** [comment]
Yes it work's but you need stand alone version of the game CCD from site (not Steam version)
Download and use revive inspector just move Starter.exe (or another .exe file) on ReviveInspector64 or 86
Then you need to choose Oculus + Monitor option in Graphic settings, click No when dialog will be (no restart game). After use free drive or mission like ever, you can see 3d in you htc vive! But befor sart all manipulations take you vive glasses on your head for good zero position

**Comment by Daddoon** [comment]
It actually works with the Steam version too.

How to:

1. Go to "C:\Program Files (x86)\Steam\SteamApps\common\City Car Driving\data\config" (or whatever path where your game is installed).
2. Open **mangalore.ini**
3. In [Graphics], change cameraAspect=0 to **cameraAspect=2** and save!
4. Go to your Revive\Revive install folder something like: "C:\Program Files\Revive\Revive"
5. Launch cmd.exe (command prompt) and type **cd "C:\Program Files\Revive\Revive"**
6. Type **ReviveInjector_x86.exe "C:\Program Files (x86)\Steam\SteamApps\common\City Car Driving\bin\win32\Starter.exe"** . Actually it may be more convenient to create a shortcut that do that for you to launch the game.
7. Steam will be launched in VR Mode. Since we have changed the cameraAspect property, it seem that it unlock the rendering configuration too (Screen, Screen + Oculus, Oculus) instead of the greyed one. Select Oculus or Screen + Oculus.
8. The game will ask to restart to take effect for theses changes. Say **NO**, because the game will be restarted without the Injector bytes...Instead, quit the game by your own, and retype the previous command / launch your injector shortcut.
9. When the game will boot, you must see your new parameters selected in the options! You will not have any VR Rendering when you are in the menus. This is normal!
10. Launch your game session.
11. ...??!!
12. Profit!
