### ISSUE TITLE
Farlands link isn't right in dashboard

### ISSUE THREAD

**Issue by AerowynX** [LibreVR/Revive#309]
With farlands it just gives error saying no oculus is connected but if I go into the folder and inject the shipping exe it works fine..

**Comment by LibreVR** [comment]
Something must've gone wrong with the executable detection.

**Comment by AerowynX** [comment]
with Farlands it is at least playable doing direct injection I can't get showdown to run in the HMD at all

**Comment by LibreVR** [comment]
Can you upload the logs from `%APPDATA%\Revive`? I'd also like to see the revive.vrmanifest from the folder where you installed Revive.

You can just copy and rename these files to a .txt extension so you can upload them in the comment box.

**Comment by AerowynX** [comment]
[ReviveInjector - Copy.txt](https://github.com/LibreVR/Revive/files/593094/ReviveInjector.-.Copy.txt)
[ReviveOverlay - Copy.txt](https://github.com/LibreVR/Revive/files/593095/ReviveOverlay.-.Copy.txt)
[revive - Copy.txt](https://github.com/LibreVR/Revive/files/593096/revive.-.Copy.txt)

**Comment by Drocona** [comment]
You have the same problem as one of mine #308 
Since LibreVR mentioned the revive.vrmanifest, I took a look into that and found the same config as you Aerowynx.
It seems this line is the culprit: "arguments": "/base \"Software/oculus-farlands/Farlands.exe\" -vr",
Where as with the injector we open "arguments": "/base \"Software/oculus-farlands/ww\Binaries\Win64\ww-Win64-Shipping.exe\" -vr",

Can we edit this manifest ourselves? Or does it get overwritten at boot of Revive?

**Comment by LibreVR** [comment]
It will only be overwritten when you update. Also, for Version 1.0 Preview 2, the `/base` argument was replace with `/library`.

**Comment by AerowynX** [comment]
ok i went ahead and edited mine will try it shortly.. still no clue what's up with showdown

**Comment by LibreVR** [comment]
This is a the same issue as #307.
