### ISSUE TITLE
Just got Dirt Rally, DOS windows flashes and nothing happens 

### ISSUE THREAD

**Issue by fabiorafa** [LibreVR/Revive#325]
I have tried so many things, patches, injector etc but the dos window flashes and nothing happens. I really, really, really would like to play this game on my Vive, it is so sad I am unable to do that. Please if anyone can help me I would appreciate it so much!!!!!!! There must be a way!

**Comment by Zyndrom** [comment]
Having the EXACT same problem..

**Comment by Rojoyinc** [comment]
mine worked last time I tried it (couple weeks ago) but I'm using older
revive setup.  Haven't gone  1.0  yet.

**Comment by euandrei** [comment]
I have the same issue with any game literally. Tried older versions of revive but not with success.  :(

**Comment by fabiorafa** [comment]
😭😭😭😭

**Comment by LibreVR** [comment]
This is because you are using the injector to start a Steam Game, that hasn't worked for Dirt Rally in a while. Never use the injector for Steam games, use the patch:

1. Extract these DLLs next to the `drt.exe` executable: https://github.com/LibreVR/Revive/releases/download/0.9.7/RevivePatch32.zip
2. Start Dirt Rally **through Steam**

Dirt Rally uses the 32-bit patch, for other Steam games use the 64-bit one: https://github.com/LibreVR/Revive/releases/download/0.9.7/RevivePatch.zip

**Comment by Zyndrom** [comment]
omg. I love u..

Thx!!


________________________________
Från: LibreVR <notifications@github.com>
Skickat: den 2 december 2016 14:42
Till: LibreVR/Revive
Kopia: Zyndrom; Comment
Ämne: Re: [LibreVR/Revive] Just got Dirt Rally, DOS windows flashes and nothing happens (#325)


This is because you are using the injector to start a Steam Game, that hasn't worked for Dirt Rally in a while. Never use the injector for Steam games, use the patch:

  1.  Extract these DLLs next to the drt.exe executable: https://github.com/LibreVR/Revive/releases/download/0.9.7/RevivePatch32.zip
  2.  Start Dirt Rally through Steam

Dirt Rally uses the 32-bit patch, for other Steam games use the 64-bit one: https://github.com/LibreVR/Revive/releases/download/0.9.7/RevivePatch.zip

-

**Comment by fabiorafa** [comment]
It worked! Thanks a lot!!!!!!!!
