### ISSUE TITLE
Windows 7 is not supported

### ISSUE THREAD

**Issue by flynn23** [LibreVR/Revive#4]
Followed instructions on the main page. Enabled outside sources. Rebooted PC. Ran SteamVR. Loaded Oculus Home, then ran LT.EXE from it's install folder. I get a window that says "No Headset".

With DreamDeck- Followed instructions. Enabled outside sources. Rebooted PC. Ran SteamVR. Loaded Oculus Home, then dragged "Dreamdeck-Win64-Shipping.exe" into "ReviveInjector.exe". Got an error box that reads "This can only be used in an Oculus headset".

I am running Windows 7 with a Vive Pre. Also running latest Steam client beta branch and latest SteamVR beta branch.

EDIT: Reverted to non-beta client and SteamVR, still have the same issues

**Comment by LibreVR** [comment]
I haven't tested this compatibility layer on Windows 7 at all. So it's probably a Windows 10 dependency somewhere, I'll try and provide support for older operating systems in the future.

**Comment by flynn23** [comment]
Yes, I also got an xinput error when trying to run DreamDeck on Windows 7. I downloaded the relevant .dll and put it in the directory, and got past the error. Unfortunately that's when it give me the "oculus only" error.

**Comment by LibreVR** [comment]
I doubt that will work, it will likely just crash Revive and then everything fails. I really can't recommend using Revive on Windows 7 until we've tested that kind of setup.

**Comment by mirh** [comment]
> I suspect that the version of XInput I'm using is not available on Windows 10.

You mean W7, right?

Anyway, I see no [_WIN32_WINNT](https://blogs.msdn.microsoft.com/chuckw/2012/04/25/xinput-and-windows-8/) define in your code, but presuming you aren't condemned to old XInput 9.1.0, I suppose that nevertheless -somehow- you are using 1.4 (which is the only other Windows SDK is able to build). 
This in turn means it's going to be available only in Windows newer than 8, since older ones just offer support up to 1.3

So, in the end, I guess your options would be requiring good old DX SDK (required for XInput 1.3) or implementing a special "dll loader" for as much unorthodox as it may be pcsx2/pcsx2@834652922a0953a17cbd8fa5063539cf0321dc1b

**Comment by jamessteininger** [comment]
I am also receiving an issue on Windows 7 with LT. The app opens but says no headset is detected.

**Comment by KLWN** [comment]
I today installed Windows 10 and now everything works aus :) BUT my 360 Controller isnt working. I have setup everything correct and it works on any other game. Advices?

**Comment by LibreVR** [comment]
Fixed in commit 548ba4590173533b3dbee40359e3a0f4935c4e5b.

@KLWN Please make a separate issue for that, also add the game you're trying to play to the description.
