### ISSUE TITLE
[Dead and Buried] Microphone Issue - Voice "Laggy"

### ISSUE THREAD

**Issue by jaorg1234** [LibreVR/Revive#401]
Hello!

Was trying to play a few matches in Dead and Buried and most people were saying that it is really difficult to understand me because my voice sounded "like a robot" and was cut off regularly. Not sure if the same thing happens in other Oculus Home games, but it was very apparent for the other people in Dead and Buried.

Hoping for a fix, as communication is what makes VR multiplayer games so great.

Edit: just tried to record my own voice with the Vive mic and it works flawlessly there. Last week when playing Raw Data haven't gotten any complaints that people are not able to understand me. First time it happened was in Dead and Buried and it is a consistent problem.

**Comment by froglegs4r** [comment]
Have the same issue as well in Dead and Buried all other games work fine

**Comment by jaorg1234** [comment]
Does the microphone work fine in other Oculus games as well? Haven't had the time to test out other multiplayer games yet

**Comment by LibreVR** [comment]
Unfortunately Revive isn't actually involved in the audio support, so this is an issue with the game itself.

The only thing related to audio that Revive is involved with is audio device selection. When the game tries to identify the Oculus headset headphones/microphone Revive will return the default audio devices.

Since your microphone is being used by the game, that means selection was done correctly and Revive is no longer involved.
