### ISSUE TITLE
#question does this emulate oculus remote?

### ISSUE THREAD

**Issue by marcos10soares** [LibreVR/Revive#424]
Is it possible to emulate oculus remote?

**Comment by LibreVR** [comment]
Yes, however due to a regression Oculus Remote support is currently broken. You can temporarily work around this by using version 1.0.2: https://github.com/LibreVR/Revive/releases/tag/1.0.2

You can activate Oculus Remote emulation by turning off one of the controllers. The remaining controller becomes an Oculus Remote.

**Comment by marcos10soares** [comment]
thanks!
