### ISSUE TITLE
Revive Appears in Dashboard but Not Functioning

### ISSUE THREAD

**Issue by ned5021** [LibreVR/Revive#426]
I own and HTC Vive

I installed Revive, Oculus Home and HTC Vive Software. 

The dashboard shows Revive and Oculus (??) but when I click on Revive nothing happens. As if I didn't click at all.

Can you please help?

**Comment by LibreVR** [comment]
Please post your logs from `%APPDATA%\Revive`? You can simply rename them to .txt files and upload them in the comment box here.

**Comment by sodre** [comment]
@ned5021 I have a faced a similar issue with other SteamVR dashboard overlay tools. If you select the *vive* app, does it work?

**Comment by ned5021** [comment]
Strangely enough, turns out when I uninstalled the Vive app and went into my games in Steam itself I would find Oculus games there! Right along with all my Steam games. 

It seems clicking on the Revive app doesn't do anything but somehow the games show up in Steam and work, possibly a new feature?

**Comment by Armada651** [comment]
Revive has had the ability to add Oculus games to your Steam library ever since it had a dashboard. Strange that the dashboard icon isn't working for you I haven't heard about anyone else running into that issue so I can't reproduce it.

Feel free to leave a comment here if you're still running into that issue.
