### ISSUE TITLE
Cat flight BBC VR 

### ISSUE THREAD

**Issue by d1360** [LibreVR/Revive#515]
It stars but cant click/keys to begin the experience. 

Wondering if a controller is required ( i dont have 1 atm) or they added Touch but not working.

**Comment by Armada651** [comment]
It uses the Oculus Remote instead of the Oculus Touch, so you'll have to turn off one of your Vive controllers. If you do that Revive will use the other one as the Oculus Remote.

Then you can just press the center of the touchpad to begin.

More info on the wiki: https://github.com/LibreVR/Revive/wiki#oculus-remote
