### ISSUE TITLE
Is there a way to not have all Revive/Oculus Home games mixed into my games list while in VR?

### ISSUE THREAD

**Issue by likwidtek** [LibreVR/Revive#523]
I would love to be able to have the option to not have Oculus Home Titles mixed into my SteamVR library but to be a separate tab or button at the bottom.  Is there a way to filter them out automatically?  It would really help.   Having them all plunked into my library by default makes everything cluttered.  Not to mention there are some redundancies when I have the same title on both platforms.

**Comment by andybak** [comment]
The main problem is that Revive titles don't behave correctly. They forget favorites and categories and defeat any attempt I make to organize them. Not sure if this is Revive specific or true of all games that appear as 'shortcuts'. But it results in the same problem.

That's the main reason I'd prefer to keep them separate - because it breaks all my filtering of other titles inside Steam

**Comment by Armada651** [comment]
This is a problem with SteamVR, you should file a bug report on their forum: https://steamcommunity.com/app/358720/discussions/

Revive registers all Oculus games it detects with OpenVR and it relies on OpenVR to store this information. SteamVR subsequently uses OpenVR to display all registered applications in your library.

**Comment by andybak** [comment]
The chance of Steam fixing this is low. A workaround from your side would have been much appreciated.

**Comment by Armada651** [comment]
Unfortunately this conflicts with another issue asking for the name of the application to show up correctly in the SteamVR Status Window. There is no way to fix both issues.

Also, Revive is not the only application adding OpenVR titles. Even if Revive would remove/hide all Oculus titles it still wouldn't fix your issue. Taking it up with Steam is really the best course of action,

**Comment by andybak** [comment]
> There is no way to fix both issues.

This is easy. If you fix the name issue then "Don't add to Steam" has the side effect of changing this behaviour. Hardly a deal breaker.

 > Also, Revive is not the only application adding OpenVR titles. 

It's the only one that I (and probably the vast majority of Vive owners) use. Viveport is the only other one and the usage of that is low (and dropping).

Is it really difficult to allow this "feature" to be disabled? I'd settle for an INI file setting if it's easier.

I jump thought hoops. The fact that basic Steam features - favourites, 'unplayed', categories etc don't work with ReVive titles is totally messing up my ability to manage my library.

**Comment by Armada651** [comment]
> Viveport is the only other one

That's not true, there are at least 4 OpenVR applications on every system that uses SteamVR:

- SteamVR Home
- SteamVR Room Setup
- SteamVR Tutorial
- SteamVR Workshop Tools

These are added by SteamVR itself.

**Comment by andybak** [comment]
OK but they aren't a big issue as there are so few of them.

The pain point is with ReVive as it adds a lot of items. And it's likely that Valve won't fix the underlying issue as it's not a big problem UNLESS you're using ReVive or another app that adds a lot of items. (and also because they are Valve and fixing bugginess in the Steam client doesn't seem to be a big priority for them in general)

Is it hugely difficult to add a switch to turn off that functionality in ReVive? Or is it more complex than that?
