### ISSUE TITLE
AirMech Command Game can not be run as Revive after updating.

### ISSUE THREAD

**Issue by c9709062** [LibreVR/Revive#537]
AirMech Command Game can not be run as Revive after updating.
Thank you for your help.

**Comment by Armada651** [comment]
AirMech now has an HTC Vive version on Steam. I recommend to try contacting the developer to see if you can get a Steam key.

**Comment by c9709062** [comment]
Thank you

**Comment by gitfat** [comment]
I've attempted to email the developer, and while browsing their Airmech Command forum on Steam, have noticed other posts from Revive users who can no longer get this game to run through Revive since the Touch update. Other games I can still play properly through Revive, but it would be nice to have this game working again, too... eventually. I don't think the developers are interested in providing Steam redemption keys...

**Comment by paulasheville** [comment]
Can we get an update on this please. I really don't want to have to buy this title again, but will if there's no other choice.

**Comment by Armada651** [comment]
It works for me with the latest version, can you try it? https://github.com/LibreVR/Revive/releases/tag/1.1.1

**Comment by c9709062** [comment]
The game will launch.
Thank you.
