### ISSUE TITLE
The Unspoken not working after the game had an update

### ISSUE THREAD

**Issue by godofdeathftw** [LibreVR/Revive#539]
Hello, after The Unspoken getting the new artifact update, the game crashes whenever me or my friend tries to enter a ranked match.  Is anyone else experiencing this?  If so, when will this be fixed?  I really want to keep my top 100 position!

**Comment by godofdeathftw** [comment]
I have the updated version of Revive btw

**Comment by Armada651** [comment]
I'm unable to reproduce the issue. Did the game happen to store a crash dump?

Also, please don't clamor for attention in other issue reports. I read every single one, but for difficult issues it's going to take longer before I can investigate the problem.

**Comment by godofdeathftw** [comment]
I'm very sorry.  I contacted the support of insomniac games, and they told me to look for a crash.dmp which I couldn't find.  They also told me to save the report from dxdiag.  I will post that file in about 8 hours.  Also, I don't know if it could have something to do with that my friend played the game in my same oculus store account (different computer), and different steam account.  He tried signing out of oculus home, but the problem still continued.

**Comment by Armada651** [comment]
Don't post your dxdiag, it can contain private information and is not all that useful. The crash dump is the thing that actually leads to a solution.

**Comment by Armada651** [comment]
If you can't find the crash dump, try and do a full process dump. Simply reproduce the crash, but instead of telling Windows to close the application, leave the crash dialog open.

Now open the task manager and in the Details tab (Processes tab on Windows 7) find `Unspoken.exe`, right-click it and click "Create dump file".

This will dump the entire memory of the process, which can be very large depending on how many resources were loaded. Try and compress it using something like 7-zip and let me know if it's a filesize you can reasonably uploaded somewhere.

**Comment by godofdeathftw** [comment]
ok, thanks

**Comment by godofdeathftw** [comment]
will do that soon
