### ISSUE TITLE
Has anyone tried Robo Recall now that it was officially patched for 360 by Epic?

### ISSUE THREAD

**Issue by lghtanddrk** [LibreVR/Revive#562]
I just read that Robo Recall was officially patched for experimental 360 support with an option to enable it in settings. 

I have been really wanting to play this but have avoided it due to the numerous Revive compatibility issues I read about.

Has anyone tried it since Epic put out the official patch yesterday?  Does it still need the RoboRevive patch now to play correctly?

And in general, how does the game play with Vive controllers?  I found Dead and Buried, Drop Dead and Ripcoil were okay but a little awkward.

Is it worth getting?

**Comment by 04nd01** [comment]
It's absolutely worth getting, even without the patch. The update makes it so you don't have to specify a direction to teleport to. Unfortunately there's a bug right now if you activate 360 mode the floor height it wrong.

**Comment by Armada651** [comment]
@04nd01 Have you tried the RoboRevive mod? https://github.com/LibreVR/RoboRevive

**Comment by 04nd01** [comment]
I have not. Am I right in assuming that this works like other RR mods, i.e. no story mode or stars?

**Comment by Armada651** [comment]
RoboRevive only enables functionality that's already part of RR, as such it won't be detected as a regular mod. So story mode and leaderboards should be available.

**Comment by 04nd01** [comment]
Cool, in that case I'll have to check it out. Thanks.

**Comment by lghtanddrk** [comment]
So to confirm, with RoboRevive is this new height issue eliminated with 360 enabled or do we need to wait for a fix?

**Comment by KilianZ** [comment]
Yes, this game is absolutely worth getting if you're even slightly interested in shooters or action games, even if there are some minor annoyances due to being designed for the Rift. It's the most fleshed out VR game you can get right now, both in quality and content. It's so much fun.

I've been playing it with RoboRevive the last few days and haven't had any issues whatsoever (haven't tried Revive since it came out). The new 360 orientation option works great and what's even better is that the performance is much better now. The game used to stutter and skip a lot with lots of stuff going on on my 980Ti using both Revive or RoboRevive.

The only "problem" I have though, is using the new 360 option removes the ability to determine where you're facing when teleporting. With the limited play space I have (barely hitting the minimum required play space) it's nice to be able to let me face in a more "safe area" where I'm not scared to hit my desk which is directly behind me.

Does anyone know if there is a way to keep the 360 option but still be able to control where you're facing? I'm pretty sure it's moddable but I'm not really familiar with UE4.

**Comment by ObliqueOne** [comment]
> So to confirm, with RoboRevive is this new height issue eliminated with 360 enabled or do we need to wait for a fix?

I am also getting this height issue, wondering if I have some thing setup wrong on my end.

**Comment by r00tuzr** [comment]
Also have height issues.

**Comment by Armada651** [comment]
Please no more reports about height issues, it's a known issue. As mentioned above, I recommend using RoboRevive. I plan to improve it soon to fix the current issues with it compared to regular Revive.

But overall the RoboRevive mod is as close to native support as we can get, so you should run into a lot less problems.

**Comment by bernardb13** [comment]
Ok...I have the updated version of RR and am using 360 degree tracking and also using RoboRevive...No issues with height at all.  Just letting the developer know in case it helps.

**Comment by r00tuzr** [comment]
I dont think there is a problem with robo-vive. Just regular revive

**Comment by Maxoxpower** [comment]
did i need to download the robo recale editor or that step is not necessary?

**Comment by Armada651** [comment]
Good news guys, I've been working on RoboRevive this week and I think I've fixed all the control scheme problems. I'm now working on packaging it as an easy-to-use installer.

**Comment by CarrotSurvivor** [comment]
You should make a post on Reddit when you fisnihs the version, explaining the height issue is fixed and that it's basically native vive support. People appreciate your work so much, as do I :) this isn't great game that everyone should be able to enjoy!

**Comment by CarrotSurvivor** [comment]
This IS a great game that everyone should enjoy ****** lol stupid spell check
