### ISSUE TITLE
Hiding Revive titles in Steam library

### ISSUE THREAD

**Issue by keffertjuh** [LibreVR/Revive#589]
I didn't see anything that looked like this one in the list of issues, so added my own.

I find the Steam big picture dashboard rather unintuitive, so I tend to look at the list of installed games and hide the ones I know I won't want to play, but people I demo might.
Issue is, when I got Revive running, any games in my Oculus library will show up as well, with uninstalling being the only way to make them go away.

This is either a question or enhancement.
Question being whether hiding these titles is already possible, enhancement being a request to make it possible.

**Comment by keffertjuh** [comment]
Just checked again and I did find a similar issue after all. 
My apologies.

**Comment by Armada651** [comment]
I do have it on my to-do list for version 1.2. The problem is, currently the Revive dashboard depends on SteamVR to register and launch these games.

I do plan to uncouple the dashboard from SteamVR and thereby making the listing in SteamVR optional, but it doesn't have as high of a priority as optimizing Revive itself.
