### ISSUE TITLE
Menu button in Wilson's Heart won't work

### ISSUE THREAD

**Issue by srt23** [LibreVR/Revive#592]
This may not be an issue with revive, as it worked the first time I tried it. Before geting in to the game you have to hold the menu button one second to recenter the view. The first time I started the game it worked as intended, but I quit the game right at the beginning to turn down supersamling. When I restarted, it won't register my menu button press. I have tried reinstalling the game, but still can't get past this point. Anyone with the same issue?

**Comment by Armada651** [comment]
The left/right controller matters, have you tried both?

**Comment by srt23** [comment]
Yeah, I have. I have been pushing everywhere on both trackpads. A lot. Very weird. Had no problems the first time around. The menu button seems to work fine in other oculus applications.

**Comment by MikeyRay1** [comment]
Having the same issue here as well except on first time startup. No issues with the button in other apps.

**Comment by srt23** [comment]
Sorry, I'm an idiot. The Vive has it's own physical menu button!

**Comment by Armada651** [comment]
Yeah, but I can see how that's an easy mistake to make, since the mapping encourages you to think of the trackpad as the actual touch controller surface. All the other buttons are mapped to the correct location.

I'm not saying I'm going to change that ofcourse, the current mapping already needs all the space it can get to feel intuitive. But I should clear up where the menu button is.
