### ISSUE TITLE
Echo Arena Free Open Beta not launching :(

### ISSUE THREAD

**Issue by CarrotSurvivor** [LibreVR/Revive#642]
the game just doesn't launch. I have tried many times, restarted oculus servive, etc. using latest version of revive. really really wanted to play this so i hope its a easy fix.

let me know what i can do to help, but the game is free to download right now. Echo Arena Open Beta.

**Comment by Armada651** [comment]
Try this release: https://github.com/LibreVR/Revive/releases/tag/1.1.5

**Comment by CarrotSurvivor** [comment]
it works! there is a pretty substantial head tracking lag, a bit sickening. Would this be due to tracking prediction? fixable? 

thanks though, at least it works now :)

**Comment by Armada651** [comment]
I did notice that during the menu, but less during the actual training. I'd have to look into that closer when it's not 3AM.

In general Revive has been stuttering a bit more since tracking prediction support was added. This requires some in-depth tweaking, but I probably won't get around to that until later.

**Comment by FlyinWhee** [comment]
I didn't notice any significant head tracking lag in game, worked pretty much out of the gate with 1.1.5 - well done sir, thanks !
