### ISSUE TITLE
Request: Option to swap Trigger and Grip function / mod-able key mappings

### ISSUE THREAD

**Issue by nvmsocool** [LibreVR/Revive#671]
Hey thank you so much for Revive, I have been using it to play Echo Arena and loving it! My only issue is that Echo Arena relies heavily on the grip button for the Vive, which is known to cause strain, and I love the game so much that I am willingly giving myself arthritis to play more :D So I was thinking it would be perfect if I could swap out the grip and trigger buttons. The Vive catches a lot of flack about the grip button so this may be a popular feature. 

It would make my day, but I understand if its not something you wish to pursue. If you don't wish to pursue, do you mind letting me know what you use to work on/compile the code/libraries I would need to make the change myself? I took a look a the InputManager.cpp script and it looks like it could be done ad-hoc there?

If you don't mind making the change, it might also be neat (for like a future feature) if you could set up like a text file that controls the key mappings for users :) 

Thanks,

Nick

**Comment by SimplexPL** [comment]
Maybe this tool will help: https://github.com/matzman666/OpenVR-InputEmulator

**Comment by Armada651** [comment]
The trigger/grip situation is a bit more exceptional. Because on the Vive controller one is analog and the other is digital, while on the Oculus Touch both are analog.

Thus if you want to switch these around you probably want to use the analog values from the trigger and not make it digital. I'll probably look into this for the next release and combine it with the Knuckles compatibility update.

**Comment by nvmsocool** [comment]
SimplexPL: I'm looking into this program as a possibility, I've managed to swap the trigger press and the grips, but the trigger tough is still unmapped... for now... Thanks for pointing me to this!

Armada651: Yeah, for my purposes its ok if they are both just true/false pressed, but full analog function for the trigger as mapped to the oculus grip would be sweet. Thanks for the update!

**Comment by MattGarten** [comment]
Being able to swap the trigger and grip would be useful for Echo and other games.  I tried using OpenVR-InputEmulator commandline swap which swapped the main trigger and grab but I think it still had the touch state of the buttons in the old positions which caused problems (worked good in the lobby and then in a match it was still trying to punch with trigger and sometimes grabbing).  Not sure how Revive handles the touch states since the Vive controller doesn't detect that.
