### ISSUE TITLE
positional stutter in Wilson's Heart and Herobound

### ISSUE THREAD

**Issue by hundenmarvin** [LibreVR/Revive#732]
In Wilson's Heart about 5 to 10 minutes into the game the positional tracking (not rotation) starts to get stuttery like it's updating only 45 times per second. This sounds exactly like reprojection but it is not. I try moving my controllers infront of me all the time and they are allways super smooth. What's peculiar is that everytime I see or interact with another character the positional tracking is smooth again. I think I have played about 45 minutes into the game. I have replayed the beginning just to check that this wasn't a one time thing.

This happens in Herobound as well. I have tested this with SteamVR beta and Revive 1.1.12 and 1.1.13. I have a gtx1080ti and using the driver 382.05 which I have heard is the last stable driver.

**Comment by sullit** [comment]
when you rolled back to 382.x did you clean install or pick the components individually? maybe check that your PhysX driver isn't still at the 384.x edge

my suspicion is that the Oculus VRapi is limiting or in some cases cert restricting frame calls now since the last update to the store app, since JBlock got a knuckles remote from Valve I suppose

**Comment by Balderick** [comment]
> my suspicion is that the Oculus VRapi is limiting or in some cases cert restricting frame calls now since the last update to the store app, and since JBlock got a knuckles remote from Valve

Recent changes to oculus runtime allowing apps from other store fronts into oculus home and SteamVR being optimised for steamvr tracked devices are probably related to what op.

**Comment by sullit** [comment]
yeah I was relating the OP issue desc to my own experience in Lone Echo recently and so correlating the response in the same way. 

it just felt like it based on updates, idk for sure based on a process trace like it would require. 

you don't think Oculus would even go to the length of securing the frame buffer in api at any point to obfuscate this util? I really hope not, the exclusives on occulus are worth the inflated value when the price isn't factored into the decision to buy them there instead of on Steam

**Comment by sullit** [comment]
the LE 3.107 patch gas fixed the pos stuttering issue, would just be a matter of waiting for the game update to correct the issue with the updated Oculus Home

**Comment by Armada651** [comment]
Please test this beta version: https://github.com/LibreVR/Revive/releases/tag/1.2.0

**Comment by Armada651** [comment]
Thanks, the beta release is still a bit buggy, so keep an eye out for the stable release once it's arrived. The update checker should just inform you of an update when the stable version is released.

**Comment by Dragoboss** [comment]
After updating to 1.2.0 user reported no further issues.
Please report back with a new ticket if this appears to be an issue again, for now I am closing this ticket, for it has gone stale.
