### ISSUE TITLE
Lone Echo ,service is unavailable !

### ISSUE THREAD

**Issue by Zony82** [LibreVR/Revive#750]
Hi i have a problem !

when i start the game , the multiplayer game.  then comes, service is unavailable !  
and the game is not starting ? why, what is the problem. Have you the same problem ?

thx Zony

**Comment by Armada651** [comment]
Did you try rebooting your PC? Are you using an HTC Vive headset?

**Comment by Zony82** [comment]
yes , i reboot every day :-) lol  but i reboot now by this problem and the problem is the same !?

No i have a 5.1 Souround System in My Room

**Comment by Zony82** [comment]
and , yes i have a HTC VIVE . REVIVE is installed, and i play Lone Echo for a Month but jet is not going and is coming the error , when i start the game ( service is unavailable )

**Comment by Zony82** [comment]
![20170829194155_1](https://user-images.githubusercontent.com/31416120/29835398-25b60af2-8cf2-11e7-868f-91bb100a8cdc.jpg)

**Comment by curlyman72** [comment]
Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Zony82 <notifications@github.com> Date: 8/29/17  10:42 AM  (GMT-08:00) To: LibreVR/Revive <Revive@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [LibreVR/Revive] Lone Echo ,service is unavailable ! (#750) 


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/LibreVR/Revive","title":"LibreVR/Revive","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/LibreVR/Revive"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Zony82 in #750: ![20170829194155_1](https://user-images.githubusercontent.com/31416120/29835398-25b60af2-8cf2-11e7-868f-91bb100a8cdc.jpg)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/LibreVR/Revive/issues/750#issuecomment-325739992"}}}

**Comment by Zony82** [comment]
?

**Comment by Zony82** [comment]
can you help mee

**Comment by Armada651** [comment]
You're going to have to be more specific, have you tried re-installing Oculus?

**Comment by Zony82** [comment]
no , i dont re-installing oculus. ok I'll try it

**Comment by Zony82** [comment]
I have uninstalled oculus software, then reinstalled oculus software and then rebooted the computer and then installed revive. if I start lone echo multiplayer now, nothing comes. I have waited 5 minutes and nothing ?????

**Comment by Armada651** [comment]
Check your firewall and networking settings, this probably indicates an actual connection issue in the game.

**Comment by Zony82** [comment]
I have no firewall I have windows defender. was for settings I need to check?

**Comment by Armada651** [comment]
This game obviously has a problem connecting to the internet on your PC likely unrelated to Revive. I don't do tech support so you'll have to figure out yourself what part of your network is preventing the connection.

**Comment by Zony82** [comment]
when i start the multiplayer game , then stay always loading and in not going , but the sound is coming .

ok , jet is coming pease updating the game from the store , but in the store is nothing update
