### ISSUE TITLE
Very poor performance in ARKTIKA.1

### ISSUE THREAD

**Issue by Buttgoblin** [LibreVR/Revive#785]
Not sure if it's just me, but my gpu usage and framerate is all over the place. GPU never maxes out and it's the same no matter the graphics quality option I use, so not too sure what's going on. Using latest Nvidia drivers.

Another, sort of unrelated issue, is that I notice I gradually get higher and higher from the floor ingame. This also happens with Wilson's heart unless I look dead ahead and press the reset position button. This stands out the most because I run Turnsignal in the middle of my play space and I end up feeling about 1ft or so off the floor.

1080ti
7820k 4.6GHz
32GB 3800MHz DDR4

**Comment by DeutschRitter** [comment]
I have experienced the same issue!

**Comment by Armada651** [comment]
Can you double-check that you're not using supersampling in SteamVR?

**Comment by Buttgoblin** [comment]
Checked and both Revive and Application Supersampling are both set to 1.0.

**Comment by Armada651** [comment]
There does seem to be a bit more overhead in the frame submission, I'll look into that further next week.

For now you can work around it by enabling Asynchronous Reprojection. If that's not enough you can *also* enable Always-on Reprojection in the developer tab. However, always keep Asynchronous Reprojection enabled.

**Comment by xMalvin** [comment]
Arktika 1.
Graphics extrem

Got to Steam VR Settings Allow Asyn off
                                          Allow Interleaved off
                                          Enable Always-on Rep on
Nvidea driver 382.53
1080ti

I got a little stuttering on the Hands, but this is ok, because the graphic is amazing.
The new NVidea driver is not so good for my system, because Robo recall is not working with it and Arktika 1 is not playable anymore on medium settings.

**Comment by DeutschRitter** [comment]
I didnt switched the drivers but with these settings it works noticeably better now on at least High settings, not perfect but still better. Thx!

**Comment by Buttgoblin** [comment]
I think I had async reprojection on before, but I'll have a look into that and always on reprojection  next time I do some VR.

Again, appreciate all your hard work and looking forward to any updates!

**Comment by hamall** [comment]
Hmm.. that's strange I seem to experience some more stuttering when enabling async reprojection with my 7700k/1080ti. I'm going to revert to 382.53 and then try again a few times.. maybe once with async only, then both, etc.. but yeah this game seems to be running very sluggishly on anything higher than med on high end computers, pretty crazy.
Thanks for actively working on this!

**Comment by xMalvin** [comment]
Update is out now.
And it works perfekt xD
Arktika.1 Graphics extrem GTX 1080TI and no stuttering.

**Comment by hamall** [comment]
Ah I just reverted back to 382.53 drivers and started using Enable Always-on Rep on. Worked like a dream with extreme settings. Tried to take off always-on but stuttering a lot. 

Malvin are you still using Enable Always-on Rep on or are you running extreme with new nvidia drivers?

**Comment by xMalvin** [comment]
I have Steam VR Settings Allow Asyn off
Allow Interleaved off
Enable Always-on Rep on
Nvidea driver 382.53

And you can find the Update in oculus Store

**Comment by Buttgoblin** [comment]
I mean, always on reprojection isn't "perfect", so I guess it's not fixed yet.

**Comment by DeutschRitter** [comment]
"Update is out now.
And it works perfekt xD
Arktika.1 Graphics extrem GTX 1080TI and no stuttering."

Where can I download the update? Is there a kind of "main page" to download different versions of revive? I always find the right page using google but for me it seems there is no "main page". All forum entries. But I am new to github ...

**Comment by hamall** [comment]
I have 'Allow app updates" on my oculus store so I'm assuming it has already updated? I was just wondering if there was a way to check.

But yeah no matter what settings I chose, Always on rep has to be on. Very strange... how can it run so perfectly with this setting? I thought it was always advised to keep this off? What exactly does this setting do that works with this game so well?

**Comment by Buttgoblin** [comment]
Any updates on this one? Itching to jump back on! Cheers!

**Comment by DeutschRitter** [comment]
Me too! Any updates?

**Comment by chrisjarramSRUK** [comment]
Well, tried all these suggestions above with my Aorus 1080ti extreme - no beef.  Still all sorts of frame rate issues where everything else runs fine.

**Comment by Armada651** [comment]
Done with my research, Arktika.1 has bad GPU utilization, because of that the Oculus SDK applies a full frame of queue ahead time.

This is basically the same as turning on Always-On Reprojection, but the Oculus SDK does that dynamically while on SteamVR this has to be done manually and is hidden as a Developer setting.

Both on SteamVR and the Oculus SDK this means the same thing: "it trades off increased positional prediction to provide more time for slower applications to render."

**Comment by Buttgoblin** [comment]
Thanks for looking into this, really appreciate it. Does that mean we just turn on always on reprojection and suck it up or is there a fix in the works?

**Comment by hamall** [comment]
Yup, just get 382.53 drivers and turn on always on repo. I tried updating to the newest drivers that everyone said got rid of vr stuttering but had to revert back to 382.53 since Arktika just wouldn't play well even with always on with newer drivers. I was never even on these 382.53 drivers.. never had any stuttering or anything other than this game which requires the older drivers and always on for a stutter free experience. btw I have 7700k and 1080Ti, so it's just something with the game.

**Comment by Armada651** [comment]
@Buttgoblin Yeah, any fix I can make will just be a hack, always-on reprojection is the only thing that approaches the Oculus runtime behaviour.

Ideally developers would design their rendering pipelines to be extremely low-latency for VR, which is what is demanded by SteamVR. Unfortunately not every developer seems to be able to do that and will instead rely on timewarp/reprojection to mask latency issues.
