### ISSUE TITLE
ADR1FT doesnt launch. only shows splash screen

### ISSUE THREAD

**Issue by WACOMalt** [LibreVR/Revive#81]

**Comment by LibreVR** [comment]
From what I've heard Adr1ft is protected by Denuvo anti-tamper software, which is designed to prevent any kind of patching. Thus it is unlikely I can ever patch this game without a huge amount of effort.

**Comment by gormanj** [comment]
I bought Adr1ft on Steam because HTC Vive support was announced as forthcoming. Adrift was very nice about supplying a key for the Oculus home version. Perhaps they will do it the other way around as well. They have stated in writing that they do not want people to have to buy the game more than once._

**Comment by Rojoyinc** [comment]
WORKS FOR ME - I read it worked so I tried it and it's so far the only game on RIFT only worth playing.  Ultra smooth I'm on  980TI  (Zotac) it's beautiful

**Comment by Rojoyinc** [comment]
CRASHED eventually when I got outside.

**Comment by Rojoyinc** [comment]
vive version is coming - so I'm not concerned about it.

**Comment by LibreVR** [comment]
Fixed now that the headset check was moved out of the DRM.
