### ISSUE TITLE
Coco VR

### ISSUE THREAD

**Issue by idsinc** [LibreVR/Revive#812]
Does not load... Shows can't find RIft...

I can load many other apps from Rift, but Coco is the only one getting this error

**Comment by matinas** [comment]
Have tried this yesterday and the app loads just fine with Revive. The issue in my case is that it gets stuck because the app couldn't recognize Oculus audio component. Maybe Revive doesn't take into account this kind of audio validations yet?

**Comment by alfrebaster** [comment]
the same error, :/

**Comment by Sithdown** [comment]
Same as @matinas, the app loads fine but can't recognize the Oculus audio headset and won't go further.

**Comment by Kiefy** [comment]
Works for me using the Patch method in the latest beta 1.2.0.2. Just adding the 3 dll's and launching the DiaVR.exe

It's a pretty cool experience.

**Comment by ytdlder** [comment]
Can confirm.

Gives "cannot find headset" error inside the app when using latest stable (1.1.14).
Hangs/crashes when using the latest beta (1.2.0b2)

**Comment by Kiefy** [comment]
Well, I don't know what makes me so special, but here's the photo I took while playing it. :)
![](https://image.prntscr.com/image/1DescUWUQsWy5KdFQKk-Xw.png)

**Comment by MJA2308** [comment]
The game is opening for me however it comes up with a blue screen saying 
"Could not detect the Rift Headset"

**Comment by greatxerox** [comment]
@Kiefy  please, where do you find the 3 dlls ?

**Comment by Kiefy** [comment]
They are added when you choose the Patch option from the Revive tray icon, then browse to and select `DiaVR.exe`

![](https://i.imgur.com/3JYSsFR.png)

Tested with Revive `1.1.14.2` and `1.2.0b2`

I can't get it to work with the Revive panel in SteamVR. even when the dll's are present.  It has to be run manually.

**Comment by greatxerox** [comment]
thank you but how do you active the Revive tray icon ?

**Comment by Kiefy** [comment]
If you've installed Revive, it should start with SteamVR.
![](https://image.prntscr.com/image/fmik88RIReyzl3xlNK6jCQ.png)

or try the [dll files](https://drive.google.com/file/d/16b0JDxqu6mf6jF7xTUfkuj883-Jak8wO/view) from my install. (If you trust me) 😈

**Comment by greatxerox** [comment]
thank you for the dll files :)

**Comment by greatxerox** [comment]
there is also THE RAVEN VR i didn't succeed to play with Revive. did you tried ?

**Comment by Kiefy** [comment]
It appears to run ok with the same dll's.
![](https://i.imgur.com/RWBblIX.png)

**Comment by greatxerox** [comment]
perfect :D

**Comment by greatxerox** [comment]
there is also OBAMA app on Oculus store which didn't work for me

**Comment by Kiefy** [comment]
That won't work with the dll's, same as the other Felix & Paul experiences, `The People's House` and `miyubi`. 

It should work with the Inject option of the tray icon, but that feature of the tray stopped working for me. I have to drag the exe's over the `ReviveInjector_x64.exe` in `C:\Program Files\Revive\Revive\` instead.
![](https://image.prntscr.com/image/B2OVBYBCSk6WyXcIIeIiGQ.png)

![](https://i.imgur.com/uoQJPIR.jpg)

This issue is going a bit off track. :P If you have problems with any other titles. should probably create new issues for them. :)

**Comment by greatxerox** [comment]
thank you you are a master :)

**Comment by ytdlder** [comment]
Still: if I try through the Steam-Revive-Page, or patched and via explorer or try Revive inject, the result is always the same: "Not Responding"

![cocovr](https://user-images.githubusercontent.com/26724958/32993746-ac2009bc-cd5c-11e7-8e89-ecc48a5c9a48.png)

**Comment by matinas** [comment]
Yup, I'm having the same results as @ytdlder

**Comment by matinas** [comment]
Well, finally I was able to play it. I have used the DLLs sent by Kiefy, restarted my PC (as I have updated Revive to version 1.1.14.2), and after launching the game through DiaVR.exe I have waited 1-2 minutes until it decided to start. Seems that it does not respond for 1 minute or so but if you wait a bit it resumes execution just fine. Hope it helps!

**Comment by ytdlder** [comment]
I thought I already waited for an eternity; but probably not :P
I'm gonna try this asap...

**Comment by ytdlder** [comment]
Ok, it really does work.

Firstly: you need to wait. Pretty long, then it starts
Secondly: my firewall blocked this app, so after waiting the experience didn't start, but a "no connection" warning was displayed

You don't need to patch it (at least with the latest beta). Just start it as all other Revive titles.

Cheers!

**Comment by Ghanth** [comment]
Hello. 
I've tried everything mentioned above and still got stuck with the "Cannot find Oculus headset" message that is preventing Coco VR to start.

**Comment by studio420** [comment]
I was still getting that missing rift hardware error, but still with patch dll's in the Coco folder.
Then I tested to update to latest Revive "Second Beta Version 1.2.0" and finally got it to run!
But not without few errors first.
When I installed the beta I got few errors so I did a full uninstall then reinstall with the beta package and got two errors after install but they were easily fixable. 
I think you will not get them errors if you just update your previous install to newest beta, I only got them because I did a fresh install with the beta installer, it must be bugged. 
If you get any of these errors, here how I fixed them.
First I got WinSparkle.dll was not found error.

```
The code execution cannot proceed because WinSparkle.dll was not 
found. Reinstalling the program may fix this problem.
```
Fix: I just downloaded WinSparkle.zip from WinSparkle homepage, extracted only the WinSparkle.dll (from /x64/release/ folder) file into root revive folder.
That error gone! 
Only to get the next error which was...
```
ReviveOverlay.exe - Point of entry was not found.
The point of entry for the process VR_InitInternal2 in the library 
link C:\ProgramFiles\Revive\ReviveOverlay.exe was not found.
```
Fix: Just copy the OpenVR API DLL from C:\Program Files\Revive\Revive\x64\openvr_api.dll to root Revive folder to fix it.

Hope this can help someone! 🔢

**Comment by greatxerox** [comment]
thank you :)

**Comment by Ghanth** [comment]
@studio420,
Your post did help ! I was reluctant to download the dll but felt safe when i read you did... ahah ! Thanks a lot. Cheers !

**Comment by Armada651** [comment]
@studio420 Sorry for that, I had to re-upload the release because it was triggering false-positives in Avira. However during the creation of the installer two dependencies were skipped. I re-uploaded the release again and it should now be fixed properly.

**Comment by adamtuliper** [comment]
Tried it with everything new downloaded today but for Windows Mixed Reality. It only worked when I chose the patch option and then manually launched DiaVRr.exe, though Revive did show up in SteamVr. My controllers (ie arms then) are reversed though - anyone see this before?

**Comment by qlyoung** [comment]
Seems like Coco works and this issue is nearly 2 years old, closing.
