### ISSUE TITLE
Blazerush camera far away

### ISSUE THREAD

**Issue by michaelmsheen** [LibreVR/Revive#86]
When I start BlazeRush the camera is set near the ground far from where I'm sitting. Resetting the seated position in SteamVR does not do anything. Any ideas for fixes?

**Comment by LibreVR** [comment]
Unfortunately Blazerush doesn't properly identify whether it is a seated or standing experience. (Very few Oculus games do)

To work around this problem use the in-game recenter function (press both thumbsticks).

**Comment by LibreVR** [comment]
I've [found a solution](https://github.com/LibreVR/Revive/commit/146b817b45b1e8019af225d9b8f0a2bdc888e8a3) to this issue which I've put in a branch.

Unfortunately this forces games such as Farlands into seated mode, but Farlands is much better in standing (room scale) mode due to the properly calibrated floor. Farlands is probably intended to be a kind of half-standing half-seated experience. Which is just a consequence of Oculus being more centered on seated experiences.

So since Blazerush has a convenient workaround, I'm going to close this issue as won't fix.
