### ISSUE TITLE
Some Oculus Home installations store games in OculusGames instead of Software

### ISSUE THREAD

**Issue by frr1** [LibreVR/Revive#87]
I installed the revive dashboard
 i see the games in the dashboard 
when I go to run a game it doesn't start 
 the dashboard just closes 
it could be Windows 7 only issue will try Windows 10 soon

**Comment by Wibz** [comment]
Well I had the same issue with Windows 10. Removing the 'run as administrator' compatibility setting on the Oculus games .exe files that was needed for the reviveinjector version of revive seems to have solved it for me.

**Comment by lucidmatt0** [comment]
Hiya. Same issue for me on Win 10 - changing "run as admin" had no effect. Selecting a game from within SteamVR just causes nothing to happen. Selecting the game again then causes the Steam VR Revive panel to disappear, but nothing else. 

Also only shows images for 3 out of the 20+ apps I've got - the rest appear as blank spaces. What am I doing wrong?

**Comment by LibreVR** [comment]
@lucidmatt0 I'm working on some logging functionality right now.

For the other issue, are you sure you have all 20 apps installed? Revive won't show apps you haven't installed yet. Also if you've newly installed these applications you have to reboot SteamVR.

**Comment by lucidmatt0** [comment]
Hi LibreVR - yes. All installed. Installed some time ago - before I switched from Rift to Vive as my go to headset. Have rebooted steamVR many times since touching Rift last.

**Comment by lucidmatt0** [comment]
BTW - I don't expect 1:1 support on this, but if my case is common and it'll help other users I'm happy to do a LMI session if a) that's helpful and b) we can find a mutual time

**Comment by LibreVR** [comment]
I think a simple logging feature will give enough information about these cases.

Also, when debugging these types of issues a Remote Debugger session is much more useful than LMI.

**Comment by lucidmatt0** [comment]
Understood. I'll watch out for the debug/logging version. Thanks

**Comment by LibreVR** [comment]
The new version with logging functionality [has been released](https://github.com/LibreVR/Revive/releases/tag/0.5.1).

Everyone who is still experiencing issues, please post your logs so we can get an idea of what the problem is.

**Comment by lucidmatt0** [comment]
Hi. Still having the same issues with 0.5.1. Here's the logs. Thanks.

[ReviveInjector.zip](https://github.com/LibreVR/Revive/files/273268/ReviveInjector.zip)

**Comment by LibreVR** [comment]
@lucidmatt0 Ok there are a couple of interesting bits in there, first the injector:

```
Creating process: C:\Program Files (x86)\Oculus\Software\epic-games-showdown\Showdown\Engine\Binaries\Win64\UE4Game-Win64-Shipping.exe
Failed to create process
```

This means the game won't even start. Can you double-check if that executable is there? And can you at least start it directly with a "No headset" error?

Now for the dashboard:

```
qrc:/Overlay.qml:53:13: QML Image: Cannot open: file:///C:/Program Files (x86)/Oculus/Software/StoreAssets/aad-productions-euclidean_assets/cover_square_image.jpg
qrc:/Overlay.qml:53:13: QML Image: Cannot open: file:///C:/Program Files (x86)/Oculus/Software/StoreAssets/baobab-studios-invasion-for-rift_assets/cover_square_image.jpg
qrc:/Overlay.qml:53:13: QML Image: Cannot open: file:///C:/Program Files (x86)/Oculus/Software/StoreAssets/cartoon-network-games-adventure-time-magic-man-s-head-games_assets/cover_square_image.jpg
qrc:/Overlay.qml:53:13: QML Image: Cannot open: file:///C:/Program Files (x86)/Oculus/Software/StoreAssets/coatsink-esper-2-pc_assets/cover_square_image.jpg
qrc:/Overlay.qml:53:13: QML Image: Cannot open: file:///C:/Program Files (x86)/Oculus/Software/StoreAssets/felix-and-paul-studios-introduction-to-virtual-reality_assets/cover_square_image.jpg
qrc:/Overlay.qml:53:13: QML Image: Cannot open: file:///C:/Program Files (x86)/Oculus/Software/StoreAssets/foo-vr-inc-foo-view_assets/cover_square_image.jpg
qrc:/Overlay.qml:53:13: QML Image: Cannot open: file:///C:/Program Files (x86)/Oculus/Software/StoreAssets/hidden-path-entertainment-dg2vr_assets/cover_square_image.jpg
qrc:/Overlay.qml:53:13: QML Image: Cannot open: file:///C:/Program Files (x86)/Oculus/Software/StoreAssets/jaunt-jaunt-vr_assets/cover_square_image.jpg
qrc:/Overlay.qml:53:13: QML Image: Cannot open: file:///C:/Program Files (x86)/Oculus/Software/StoreAssets/llyr-ap-cenydd-ocean-rift-pc_assets/cover_square_image.jpg
qrc:/Overlay.qml:53:13: QML Image: Cannot open: file:///C:/Program Files (x86)/Oculus/Software/StoreAssets/oculus-dreamdeck_assets/cover_square_image.jpg
qrc:/Overlay.qml:53:13: QML Image: Cannot open: file:///C:/Program Files (x86)/Oculus/Software/StoreAssets/oculus-henry_assets/cover_square_image.jpg
qrc:/Overlay.qml:53:13: QML Image: Cannot open: file:///C:/Program Files (x86)/Oculus/Software/StoreAssets/oculus-lost_assets/cover_square_image.jpg
qrc:/Overlay.qml:53:13: QML Image: Cannot open: file:///C:/Program Files (x86)/Oculus/Software/StoreAssets/oculus-oculus-360-photos_assets/cover_square_image.jpg
qrc:/Overlay.qml:53:13: QML Image: Cannot open: file:///C:/Program Files (x86)/Oculus/Software/StoreAssets/oculus-oculus-video_assets/cover_square_image.jpg
qrc:/Overlay.qml:53:13: QML Image: Cannot open: file:///C:/Program Files (x86)/Oculus/Software/StoreAssets/penrose-the-rose-and-i_assets/cover_square_image.jpg
qrc:/Overlay.qml:53:13: QML Image: Cannot open: file:///C:/Program Files (x86)/Oculus/Software/StoreAssets/zen-pinball-zen-pinball-vr_assets/cover_square_image.jpg
```

This means it wasn't able to load the cover images for more than half of the games you have. Which is very strange, since Oculus Home should cache these images for all your installed games.

**Comment by lucidmatt0** [comment]
Hiya. Although there's a ..Oculus\Software folder, all the files are under ..Oculus\OculusGames

E.g. C:\Program Files (x86)\Oculus\OculusGames\epic-games-showdown\Showdown\Engine\Binaries\Win64

I've not mucked around with the location, so not sure what's going on there...

Similar story with the cover images - the storeassets folder is also in "OculusGames" folder rather than "Software". 

Not sure if it's safe to just copy stuff to the "Software" folder given that there may be registry settings used by the rift games pointing to the "OculusGames" folder?

**Comment by lucidmatt0** [comment]
![image](https://cloud.githubusercontent.com/assets/1594121/15407736/5e9d1ec2-1e04-11e6-8bae-b22bcd55bc59.png)

Here's a screenie.

**Comment by lucidmatt0** [comment]
Heh. Was as simple as copying the folders for LT game and assets from OculusGames to Software folder.

LT works, and all games are showing on the panel.

Thanks for the help. Will try copying the other games and seeing if that works.

Not sure how many other people will have "OculusGames" as the default folder instead of "Software"?

**Comment by LibreVR** [comment]
Ugh, now I've got to find where this is decided. Why do they even have two different names for this?

**Comment by LibreVR** [comment]
@lucidmatt0 When did you install Oculus Home? Was it recently or more than a month ago? Maybe they changed the folder name, but still support it for backwards compatibility?

**Comment by lucidmatt0** [comment]
Perhaps it's worth parameterising it and letting the user override a default value? Even if it's only in a ini file for now?

When did it arrive? 12th of April if that helps.

Regardless - thanks for doing all this. It works really well and to a layman is pure wizardry!

**Comment by LibreVR** [comment]
Yeah, so I think they changed that from `OculusGames` to `Software` recently. Not sure what to do about it, I could check both locations to see where the file actually exists. I don't think there's a single option for it since it seems you have apps in both locations.

I'm tempted to just leave it since it should become less and less common. You should be able to just move all files into the `Software` folder and be done with it.

**Comment by lucidmatt0** [comment]
Could do, or default it to "software" but let the user change it in an ini file?

Either way I've just been through most apps after *copying* them from oculusgames to software folder. Most work bar showdown and zen pinball. Will try removing all games from oculusgames to prove that just moving the games to software folder works.

**Comment by gormanj** [comment]
There is an HTC Vive version of Showdown.

**Comment by lucidmatt0** [comment]
Thanks gormanj.

BTW. Will try and remove all files in OculusGames later on tonight to prove that just moving files from OculusGames to Software resolves the issue.

**Comment by LibreVR** [comment]
It looks like the latest update of Oculus Home has made the file structure consistent again.
