### ISSUE TITLE
Oculus not working with Revive on WMR

### ISSUE THREAD

**Issue by Kingjazzblue** [LibreVR/Revive#888]
Hello,
I downloaded Steam VR, Oculus app, and Revive. I have a Dell Visor with controllers, and they work great in the Windows VR and Steam app, but when I launched Oculus and Steam VR, then clicked the Revive button, all apps from Oculus went grey and errors started flashing on my computer. I closed everything and tried again. Same thing. I have currently only tried Face your Fears and the Carnival on Oculus, neither worked. I didn't want to buy games until I knew Revive would work. 
How can I get this to work? I just downloaded the everything tonight, could Oculus have updated their software to stop Revive?
Thank you for helping

**Comment by Armada651** [comment]
Revive doesn't officially support WMR yet, I'm working on a version specifically developed for WMR. Until then you may run into strange issues with WMR.

**Comment by Kingjazzblue** [comment]
Thank you very much. From what I've heard, you are doing an incredible job. I greatly look forward to the MWR update.

**Comment by HAWK331** [comment]
I agree with King.. you are doing a great job..  I also run the WMR..  King.. did you try loading revive the last version before this one?   was thinking of trying this because  Elite Dangerous runs when I run the Steam version, but when I try to run the version from Oculus,  it will only load on PC screen and not in VR  :(  it's like you have to roll the dice for now..  can't wait for the WMR version..  *gives Armada a cyber manhug*   Thank you

**Comment by Kingjazzblue** [comment]
Hi Hawk, 
I haven't tried running the previous version yet, but I shall tomorrow. Thank you for the suggestion. I'll let you know how it goes.

**Comment by Kingjazzblue** [comment]
Hi Hawk,
I tried the previous version and unfortunately I was having the same issues. I was able to get some games sort of working, but when you turn too fast then the screen dropped out of the VR. I can't wait Windows Mixed Reality version of ReVive.

**Comment by VladislavKostin** [comment]
It's weird because mine worked perfectly at first and then just stopped. I can see the list of Oculus games in SteamVR but clicking on them does nothing.

**Comment by ajsw78** [comment]
please help not to much computer lingo where...I just got into vr and all I want to do is share it with my son...I bought a game called dirt rally and also bought an account from windows market minecraft...and I heard if you had an oculus rift attached to the computer they both would start automatically in vr...I dont understand whats going on please help...I got it to a part where i can open my revive and lets me see contents of the oculus but i am not able to play any games due to errors...please please help me out and getting this to work...

**Comment by ajsw78** [comment]
Thanks for the reply...my comp specs are gpu its a gtx 1050 and processor
i7 7700 what more info to give you...hahaha sorry i am not a computer
guy...im sorry about your house hope all is well now

**Comment by TrickyDee42** [comment]
Great news about the WM<R version, any idea when we may see a version, I'll not hold you to it, just a rough idea how it is going.
If you need any testers, Lenovo with RX470 8gb nitro + here.

**Comment by aleph99** [comment]
Same here. Lenovo WMR with top-spec desktop (GeForce 1080i, etc.), working fine with WMR and Steam, but all Revive games & apps only open in the PC screen and sometimes I get errors about Oculus not find my device. I tried disabling antivirus as suggested somewhere, but that did not work. Any news on WMR support?
