### ISSUE TITLE
Everything in WMR appears very close as and unatural

### ISSUE THREAD

**Issue by mark1616** [LibreVR/Revive#893]
Hi, with the Lenovo Explorer anything I play from Oculus gives the feeling that it is too close you my face. I'm not an expert but this could be that it is mapping the two views too close together as if my eyes were not as far apart. Playing anything in the Mixed Reality portal and 'normal' Steam games are all perfectly fine. Is there something that can be scripted to adjust this?

**Comment by Armada651** [comment]
You have good eyes, indeed it looks like WMR doesn't report the correct matrix in response to `GetEyeToHeadTransform()`. Which is strange, because it does report the correct IPD in response to a `Prop_UserIpdMeters_Float` query.

I can implement a workaround, but I would really prefer that Microsoft fixes this in their driver.

**Comment by tamer82** [comment]
Maybe it can be added as a hack that can be disabled in advanced settings or even from the Lua script?

**Comment by Armada651** [comment]
It will be added as a hack, but there's no reason why you'd ever want to disable it so I'm not doing that. There's already a system in place to use different behaviors based on which driver or game is loaded

**Comment by Armada651** [comment]
Fixed in version 1.2.1, please download the latest release.

**Comment by boynet** [comment]
@Armada651 hi sorry to bother you, is there any bug I can report to the wmr devs? they are active on the [wmr steamcommunity](http://steamcommunity.com/app/719950/discussions/)

**Comment by Armada651** [comment]
@boynet You can tell them they haven't implemented `GetEyeToHeadTransform()` which Revive normally relies on.

**Comment by benbuzbee** [comment]
Hey @Armada651 ,
I'm an Engineer for Microsoft's WMR support for SteamVR.
In WMR, GetEyeToHeadTransform(Left) is Identity. That is because the pose we report in poses[0].mDeviceToAbsoluteTracking is exactly the pose of the left eye. GetEyeToHeadTransform(Right) is the correct translation from the left eye (i.e. the pose) to the right eye.

That means that for either eye you should get the correct view transform like this, assuming Load is a function that turns the OpenVR matrix into a XMMATRIX:

`const auto view = XMMatrixInverse(nullptr, Load(poses[0].mDeviceToAbsoluteTracking)) * XMMatrixInverse(nullptr, Load(system->GetEyeToHeadTransform(element.eye)))`

There is a rotation between eyes, so using pure IPD to transform between the two will introduce some issues when combined with WMR overlays like notifications or boundaries.

**Comment by Armada651** [comment]
That's surprising to hear, that's not what `poses[0].mDeviceToAbsoluteTracking` is supposed to be. I'll disable the hack, but whether that kind of eye transform is correctly applied is entirely up to the game. Since I don't control how an Oculus game constructs the view matrix.

Does the `SpatialLocator` in the native API also report the left eye pose instead of the pose of the headset?

**Comment by benbuzbee** [comment]
ISpatialLocator returns a position at the center of rotation of the head, not the left eye. For re-projection to work correctly, however, you must **render** with the view matrices returned from IHolographicCameraPose::TryGetViewTransform. The SteamVR bridge reports the left eye because it can be exactly the inverse of this. There is no way to perfectly correlate the spatial location at frame time with the view matrices you were expected to render with, although you can get close.

We could cheat our way out of it by reporting the pose at the spatial locator, then reporting the EyeToHeadTransform's as the relative transform between the inverse view matrix and the spatial locator pose, but there has been no reason to add that extra complexity, and it might not work since that transformation would change frame-over-frame, any app that caches it would render incorrectly.

**Comment by Armada651** [comment]
@benbuzbee I assumed that if you supply `TryLocateAtTimestamp()` with the `PerceptionTimestamp` of the right frame you would get the headpose that was used to construct the view matrices for that frame.

Is that what you mean when you say you can get "very close"?

**Comment by benbuzbee** [comment]
Yeah that's "very close". You may notice reprojection artifacts if you render with it. If you have the ability to change the head to eye transforms per frame, that's a fine way to go as long as your head to eye transforms are recalculated based on the view matrix. 

For our SteamVR support we don't have the luxury.

**Comment by Armada651** [comment]
@benbuzbee I'm working on a version of Revive that works without SteamVR right now. Would you be interested in setting up a call so we can discuss some of these differences more in-depth? My e-mail is jules.blok@gmail.com

**Comment by Gineton2** [comment]
I'm trying The Climb with Revive 1.3.0 on an Acer MR headset, Windows build 1803 with SteamVR Beta and WMR for SteamVR Beta. When I launch with SteamVR, performance is expected, but everything is monoscopic. 

When I launch straight from Revive/Remixed, performance is at best 60fps but seems stereoscopic. Alt-Tabbing does not seem to help.
 
I do not have the monoscopic issue when playing First Contact with SteamVR.
