### ISSUE TITLE
paying you

### ISSUE THREAD

**Issue by ConorKnoxx** [LibreVR/Revive#915]
This seems like the "wrong" place for this... but I couldn't find anywhere else really (not very familiar with github at all...)
I was thinking about the work that must go into this, and how crappy the situation would be without Revive... so I thought I should "pay" something for the privilege...
It seems like the my only choice is Patreon, as a monthly subscription though? I hate subscriptions. On top of that - it seems I'm locked between either $1 per month or next is $5 per month. Nothing in between? Is there some way to just send a "one time donation"? 
I have to think there is / might be many others out here with the same thoughts?

**Comment by ajayyy** [comment]
On patreon you can set one in the middle, you just will get only the rewards for the lower tier

**Comment by boynet** [comment]
I totally missed the fact he had a patreon, I always look at the end of readme for patreon will be good idea to add it to there also

**Comment by Armada651** [comment]
Fixed in commit 7f4093a6dd051ac68f65416f1417ac6336ea9a80.

After selecting a tier you can just enter a custom amount if you want. Recurring donations are more effective than one-time donations, since recurring donations provides a more reliable revenue stream. It may seems counter-intuitive but I'd rather you donate $1 per month for a year than pay me $12 at once.

If you really want to make a one-time donation, just become a patron and immediately cancel. You'll be charged for the first month right away, but not for the upcoming months.
