### ISSUE TITLE
.exe files will not download

### ISSUE THREAD

**Issue by KILLERbeast61** [LibreVR/Revive#975]
I have downloaded oculus home and revive, I downloaded my games and tried to boot them but they crash/close immediately. I looked in the programs/oculus/software/software/__insert game folder___ and I've noticed the .exe files are not downloading. I have uninstalled and reinstalled oculus home and this has not helped. I also don't know where to find the app data file so i can delete. I think I missed something, or maybe oculus program is intentionally trying to keep me from playing on revive mod. please help

**Comment by Dragoboss** [comment]
When you first started the Oculus software did you skip the first set-up procedure?
Maybe try deleting all data in Oculus/software/software folders and re-try downloading one of the games.

I have not seen any previous problems downloading the executables because of Revive.... I don't think that's a thing.
