### ISSUE TITLE
Mic Not Working

### ISSUE THREAD

**Issue by PapaCarrot** [LibreVR/Revive#995]
Hello. I was able to use my HTC Vive microphone in all normal games, but when I use Revive, my mic doesn't work. I tried it in a few multiplayer games, such as Echo Arena, yet none of them allowed me to use my mic.

**Comment by qlyoung** [comment]
@PapaCarrot Hey, I tried this with Revive 1.8.1 in Echo Arena and it worked for me, although I had to change the following:

1. Set the Vive mic to default recording device and default communications device in the Windows sound control panel
2. Make sure SteamVR isn't set to change the recording device
3. Turn of push to talk in Advanced Settings
4. Do a mic test through the VR settings panel
5. Turn off push to talk in Echo Arena

Hope this helps. Closing since I can't repro it.
